-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 18:11:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chinabridge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chinabridge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chinabridge` DEFAULT CHARACTER SET utf8 ;
USE `chinabridge` ;

-- -----------------------------------------------------
-- Table `chinabridge`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`device` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`device` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `device_id` VARCHAR(100) NOT NULL,
  `device_info` VARCHAR(100) NULL DEFAULT NULL,
  `push_token` TEXT NULL DEFAULT NULL,
  `validate` TINYINT(1) NOT NULL DEFAULT '0',
  `date_creation` BIGINT(20) NOT NULL DEFAULT '0',
  `bonus_flag` INT(11) NOT NULL DEFAULT '0',
  `type` VARCHAR(30) NOT NULL,
  `date_last_connection` BIGINT(20) NOT NULL DEFAULT '0',
  `date_inactive_apns` BIGINT(20) NOT NULL DEFAULT '0',
  `inactive_apns` TINYINT(1) NOT NULL DEFAULT '0',
  `lang` VARCHAR(10) NOT NULL DEFAULT 'en',
  `client_version` VARCHAR(20) NOT NULL DEFAULT '0.0.0',
  `last_player_id` BIGINT(20) NOT NULL DEFAULT '0',
  `push_fcmToken` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_device` USING BTREE (`device_id`) ,
  INDEX `idx_last_player` USING BTREE (`last_player_id`) )
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`player` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`player` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `lang` VARCHAR(20) NOT NULL DEFAULT 'en',
  `display_lang` VARCHAR(10) NOT NULL,
  `creation_date` BIGINT(20) NOT NULL DEFAULT '0',
  `last_creation_date` BIGINT(20) NOT NULL DEFAULT '0',
  `credit_amount` INT(11) NOT NULL DEFAULT '0',
  `date_last_credit_update` BIGINT(20) NOT NULL DEFAULT '0',
  `nb_played_deals` INT(11) NULL DEFAULT '0',
  `firstname` VARCHAR(45) NOT NULL DEFAULT '',
  `lastname` VARCHAR(45) NOT NULL DEFAULT '',
  `sex` SMALLINT(6) NOT NULL DEFAULT '0',
  `country_code` VARCHAR(10) NOT NULL DEFAULT '',
  `display_country_code` VARCHAR(10) NOT NULL,
  `town` VARCHAR(45) NOT NULL DEFAULT '',
  `description` VARCHAR(256) NOT NULL DEFAULT '',
  `avatar_present` TINYINT(1) NOT NULL DEFAULT '0',
  `birthday` DATE NULL DEFAULT NULL,
  `settings` TEXT NULL DEFAULT NULL,
  `convention_profile` INT(11) NULL DEFAULT '-1',
  `subscription_expiration_date` BIGINT(20) NOT NULL DEFAULT '0',
  `credentials_init_mask` INT(11) NULL DEFAULT NULL,
  `last_connection_date` BIGINT(20) NULL DEFAULT NULL,
  `friend_flag` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_player_mail` (`mail` ASC) ,
  UNIQUE INDEX `idx_pseudo` (`nickname` ASC) ,
  INDEX `idx_firstname` USING BTREE (`firstname`) ,
  INDEX `idx_player_country` USING BTREE (`country_code`) ,
  INDEX `idx_player_lastname` USING BTREE (`lastname`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`player_device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`player_device` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`player_device` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `pla_id` BIGINT(20) NOT NULL,
  `device_id` BIGINT(20) NOT NULL,
  `date_creation` BIGINT(20) NOT NULL DEFAULT '0',
  `date_last_connection` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_player_device_device` USING BTREE (`device_id`) ,
  INDEX `fk_player_device_pla` USING BTREE (`pla_id`) ,
  INDEX `idx_pla_dev` USING BTREE (`pla_id`, `device_id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`player_duel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`player_duel` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`player_duel` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `player1` BIGINT(20) NOT NULL,
  `player2` BIGINT(20) NOT NULL,
  `date_creation` BIGINT(20) NOT NULL,
  `duel_status` INT(11) NULL DEFAULT '0',
  `reset_request` INT(11) NULL DEFAULT '0',
  `nb_played` INT(11) NULL DEFAULT '0',
  `nb_win_pla1` INT(11) NULL DEFAULT '0',
  `nb_win_pla2` INT(11) NULL DEFAULT '0',
  `date_reset` BIGINT(20) NULL DEFAULT '0',
  `date_last_duel` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idx_pladuel_pla1` USING BTREE (`player1`) ,
  INDEX `idx_pladuel_pla2` USING BTREE (`player2`) ,
  INDEX `idx_status_date` USING BTREE (`duel_status`, `date_creation`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`player_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`player_link` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`player_link` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `player1` BIGINT(20) NOT NULL,
  `player2` BIGINT(20) NOT NULL,
  `type_mask1` INT(11) NOT NULL DEFAULT '0',
  `type_mask2` INT(11) NOT NULL DEFAULT '0',
  `date_link` BIGINT(20) NOT NULL DEFAULT '0',
  `date_msg_reset1` BIGINT(20) NOT NULL DEFAULT '0',
  `date_msg_reset2` BIGINT(20) NOT NULL DEFAULT '0',
  `message` VARCHAR(256) NOT NULL DEFAULT '',
  `date_last_message` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idx_plaLink_pla1` USING BTREE (`player1`) ,
  INDEX `idx_plaLink_pla2` USING BTREE (`player2`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`product` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(100) NOT NULL,
  `enable` TINYINT(1) NOT NULL DEFAULT '0',
  `prod_cat` INT(11) NOT NULL DEFAULT '0',
  `amount_credit` INT(11) NOT NULL DEFAULT '0',
  `bonus` TINYINT(4) NOT NULL DEFAULT '0',
  `type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `label_fr` VARCHAR(50) NULL DEFAULT NULL,
  `label_en` VARCHAR(50) NULL DEFAULT NULL,
  `name_c3po` VARCHAR(100) NULL DEFAULT NULL,
  `original_product_id` VARCHAR(100) NULL DEFAULT NULL,
  `color` VARCHAR(100) NULL DEFAULT NULL,
  `credit_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_name_c3po` USING BTREE (`name_c3po`) ,
  INDEX `idx_productID` USING BTREE (`product_id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT '',
  `creation_date` BIGINT(20) NOT NULL,
  `category` BIGINT(20) NOT NULL,
  `result_type` INT(11) NULL DEFAULT NULL,
  `deal_count` INT(11) NOT NULL,
  `begin_date` BIGINT(20) NOT NULL,
  `last_start_date` BIGINT(20) NOT NULL DEFAULT '0',
  `end_date` BIGINT(20) NOT NULL,
  `number` INT(11) NULL DEFAULT '-1',
  `valid` TINYINT(1) NOT NULL DEFAULT '0',
  `finished` TINYINT(1) NOT NULL DEFAULT '0',
  `engine_version` INT(11) NOT NULL DEFAULT '0',
  `nb_player` INT(11) NULL DEFAULT '0',
  `serie` VARCHAR(2) NOT NULL DEFAULT '??',
  `nb_max_player` INT(11) NOT NULL DEFAULT '-1',
  `nb_credit_play_deal` INT(11) NOT NULL DEFAULT '1',
  `settings` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_tour_cat_date` USING BTREE (`category`, `begin_date`, `end_date`) ,
  INDEX `idx_tour_cat_finish` USING BTREE (`category`, `finished`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament_category` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `stat_result_type` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_type` (`type` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament_challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament_challenge` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament_challenge` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tournament_type` BIGINT(20) NOT NULL,
  `pla_creator` BIGINT(20) NOT NULL,
  `pla_partner` BIGINT(20) NOT NULL,
  `date_creation` BIGINT(20) NOT NULL,
  `date_expiration` BIGINT(20) NOT NULL,
  `status` INT(11) NOT NULL DEFAULT '0',
  `settings` TEXT NULL DEFAULT NULL,
  `tournament_table` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament_deal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament_deal` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament_deal` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `distrib_id` BIGINT(20) NOT NULL,
  `tour_id` BIGINT(20) NOT NULL,
  `idx_tour` INT(11) NOT NULL,
  `nb_player` INT(11) NOT NULL DEFAULT '0',
  `score_average` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_td_tour_idx` (`tour_id` ASC, `idx_tour` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament_distribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament_distribution` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament_distribution` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dealer` VARCHAR(1) NOT NULL,
  `vul` VARCHAR(1) NOT NULL,
  `cards` VARCHAR(52) NOT NULL,
  `param_generator` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_distrib_cards` USING BTREE (`cards`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament_game2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament_game2` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament_game2` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deal_id` BIGINT(20) NOT NULL,
  `table_id` BIGINT(20) NOT NULL,
  `finished` TINYINT(1) NOT NULL DEFAULT '0',
  `rank` INT(11) NULL DEFAULT NULL,
  `result` FLOAT NULL DEFAULT NULL,
  `bids` VARCHAR(256) NULL DEFAULT NULL,
  `cards` VARCHAR(256) NULL DEFAULT NULL,
  `tricks_winner` VARCHAR(13) NULL DEFAULT NULL,
  `contract_type` INT(11) NULL DEFAULT NULL,
  `contract` VARCHAR(2) NULL DEFAULT NULL,
  `declarer` VARCHAR(1) NULL DEFAULT NULL,
  `tricks` INT(11) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `convention` VARCHAR(128) NULL DEFAULT NULL,
  `start_date` BIGINT(20) NOT NULL,
  `last_date` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`tournament_table2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`tournament_table2` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`tournament_table2` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tour_id` BIGINT(20) NOT NULL,
  `creator_id` BIGINT(20) NOT NULL,
  `pla_south` BIGINT(20) NOT NULL,
  `pla_north` BIGINT(20) NULL DEFAULT NULL,
  `pla_west` BIGINT(20) NULL DEFAULT NULL,
  `pla_east` BIGINT(20) NULL DEFAULT NULL,
  `nb_deal_played` INT(11) NOT NULL DEFAULT '0',
  `current_game` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chinabridge`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chinabridge`.`transaction` ;

CREATE TABLE IF NOT EXISTS `chinabridge`.`transaction` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT(20) NOT NULL,
  `player_id` BIGINT(20) NOT NULL,
  `version` VARCHAR(15) NULL DEFAULT NULL,
  `transaction_date` BIGINT(20) NULL DEFAULT NULL,
  `information` TEXT NULL DEFAULT NULL,
  `store_transaction_id` VARCHAR(100) NULL DEFAULT NULL,
  `transaction_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_date` USING BTREE (`transaction_date`) ,
  INDEX `idx_player` USING BTREE (`player_id`) ,
  INDEX `idx_product` USING BTREE (`product_id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
