package com.funbridge.server.ws.support;

public class WSSupConstantes {
	public static String EXCEPTION_COMMON_SERVER_ERROR = "ERROR_SERVER";
	public static String EXCEPTION_COMMON_PARAM_NOT_VALID = "PARAMETER_NOT_VALID";
    public static String EXCEPTION_COMMON_NOT_IMPLEMENTE = "NOT_IMPLEMENTED";
	public static String EXCEPTION_COMMON_PLAYER_CONNECTED = "PLAYER_CONNECTED";
	public static String EXCEPTION_PLAYER_MAIL_EXISTING = "MAIL_EXISTING";
	public static String EXCEPTION_PLAYER_PSEUDO_EXISTING = "PSEUDO_EXISTING";
	public static String EXCEPTION_PLAYER_PASSWORD_NOT_VALID = "PASSWORD_NOT_VALID";
	public static String EXCEPTION_PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND";
	public static String EXCEPTION_COMMON_DEPRECATED = "METHOD DEPRECATED";
}
