package com.gotogames.bridge.engineserver.ws;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name="type")
public enum ServiceExceptionType {
	COMMON_INTERNAL_SERVER_ERROR("ERROR INTERNAL"),
	COMMON_PARAMETER_NOT_VALID("THE PARAMETER IS NOT VALID"),
	COMMON_DEPRECATED("THIS METHOD IS DEPRECATED - DON'T USED IT !"),
	COMMON_NOT_IMPLEMENTED("THIS METHOD IS NOT IMPLEMENTED - DON'T USED IT NOW !"),
	SESSION_INVALID_CHALLENGE("THE RECEIVED CHALLENGE IS NOT VALID"),
	SESSION_UNKNOWN_LOGIN("THE LOGIN IS UNKNOWN"),
	SESSION_INVALID_SESSION_ID("THE SESSION ID IS NOT VALID"),
	SESSION_MESSAGE_NOT_VALID("THE MESSAGE IS NOT VALID"),
	SESSION_USER_TYPE_NOT_VALID("THE TYPE OF USER IS NOT VALID FOR THIS SERVICE"),
	SESSION_NO_ENGINE_CONNECTED("NO ENGINE USER CONNECTED")
	;
	
	private String msg;
	ServiceExceptionType(String txt) {
		this.msg = txt;
	}
	
	public String getMessage() {
		return this.msg;
	}
}
