package com.gotogames.bridge.engineserver.test;

import java.util.Random;

import com.gotogames.bridge.engineserver.common.Constantes;
import com.gotogames.bridge.engineserver.common.EngineConfiguration;
import com.gotogames.bridge.engineserver.ws.compute.WSComputeQuery;
import com.gotogames.common.tools.StringTools;


public class QueryTest {

	private static String[][] gameTest = new String[][] {
			new String[] {
					"N",
					"L",
					"NWSWSNWESNEWNWNWSEEESENWNSEESSSEEEENSSWWWWNNENSWWSNN",
					"1SN-PAE-2HS-PAW-3CN-PAE-3NS-PAW-PAN-PAE",
					"2DW-JDN-7DE-5DS-5SN-7SE-QSS-2SW-9SS-TSW-ASN-7HE-KSN-6DE-4CS-3SW-JHN-2HE-4HS-AHW-JSW-6SN-3HE-6CS-4SW-8SN-8DE-5HS-ACN-9CE-TCS-3CW-KDN-TDE-9DS-4DW-3DN-8HE-ADS-QDW-KHS-KCW-JCN-THE-QHS-8CW-7CN-9HE-6HS-5CW-2CN-QCE" },
			new String[] {
					"E",
					"N",
					"WNWWEWNNENWESNWSSSWNEEWEWESSNWNWNSEWSWSSNNEESNEENSSE",
					"1SE-2HS-3CW-PAN-3DE-3HS-X1W-PAN-4HE-X1S-4NW-PAN-5HE-PAS-6DW-PAN-PAE-PAS",
					"AHS-5HW-4HN-THE-4DS-3DW-8DN-TDE-9DE-5DS-JDW-2DN-7HW-8HN-ADE-2HS-QDE-6DS-KDW-6HN-2CW-8CN-KCE-ACS-KSS-JHW-4SN-ASE-6CE-3HS-4CW-9CN-3SN-TSE-QSS-7DW-QCW-3CN-TCE-2SS-5CW-JCN-6SE-7SS-8SN-9SE-9HS-7CW-5SE-QHS-KHW-JSN" },
			new String[] {
					"S",
					"E",
					"SSWEWSSWWWEEENNESNWNNNSSSWNEESENWENWESWNSNSWWEEESWNN",
					"PAS-1CW-PAN-1HE-1SS-X1W-3SN-4HE-X1S-PAW-4SN-PAE-PAS-PAW",
					"AHW-2HN-3HE-5HS-8HW-7HN-QHE-KHS-KDS-ADW-2DN-4DE-JHW-THN-4HE-3SS-JSS-QSW-KSN-8SE-ASN-9SE-5SS-6SW-4SN-TSE-2CS-7SW-ACE-3CS-4CW-2SN-3DN-5CE-QDS-7DW-JDS-6CW-6DN-QCE-5DS-9CW-TDN-6HE-9DN-KCE-8CS-JCW-8DN-9HE-7CS-TCW" },
			new String[] {
					"W",
					"A",
					"NNESSWEWNNSWNNEEWEWWNSWWSNESNEEEWENWNSSSENSWEWSWNSES",
					"PAW-1CN-PAE-2SS-PAW-4SN-PAE-4NS-PAW-5HN-PAE-5NS-PAW-6CN-PAE-7NS-PAW-PAN-PAE",
					"QDW-2DN-3DE-KDS-QCS-7CW-2CN-8CE-6CS-9CW-TCN-4CE-ACN-4DE-5CS-KCW-JCN-2HE-2SS-7DW-3CN-6DE-5SS-6SW-4SN-7SE-QSS-8SW-TDS-5DW-9DN-5HE-3HS-8HW-QHN-6HE-ADN-7HE-9SS-8DW-THN-9HE-AHS-JHW-KHS-JDW-4HN-KSE-ASS-TSW-JSN-3SE" },
			new String[] {
					"N",
					"N",
					"WEWWNENWSNEENNWEENSEWSSSWSSNNWNSWNWSSWSEEESNENEEWWSN",
					"PAN-PAE-1NS-PAW-2CN-PAE-3NS-PAW-PAN-PAE",
					"5HW-6HN-7SE-7HS-AHS-8HW-3HN-4DE-JHS-KHW-4HN-7CE-3DW-6DN-8DE-TDS-QHS-THW-9HN-2SE-2HS-5CW-6CN-3SE-JDS-KDW-2DN-5DE-9DW-6SN-4SE-QDS-ADS-2CW-8CN-3CE-7DS-4CW-JCN-9SE-KSS-JSW-8SN-TSE-TCS-9CW-ACN-KCE-ASN-QCE-5SS-QSW" },
			new String[] {
					"E",
					"E",
					"NSNNSNWEEENSWWWSNSWWSSWWWEWSWNNSNNNENSSEESWEWNEEEESE",
					"1SE-PAS-2DW-2SN-2NE-4HS-PAW-PAN-PAE",
					"7SW-8SN-ASE-4SS-ADE-4DS-KDW-5DN-JCE-3CS-ACW-2CN-8CW-4CN-9CE-KCS-AHS-4HW-5HN-JHE-3HS-2HW-6HN-TCE-QHN-QSE-KHS-5SW-7HS-QDW-THN-JSE-9HN-TSE-KSS-JDW-8HN-9SE-6CS-8DW-QCN-6SE-TDS-7DW-7CN-3SE-9DS-3DW-5CN-2SE-6DS-2DW" },
			new String[] {
					"S",
					"A",
					"EEEWESNWNESNWWSNSEWWSWSWSEEWNWEWNNNENNESEWSNESWNSSSN",
					"1SS-PAW-2HN-PAE-2SS-PAW-4DN-PAE-5DS-PAW-6SN-PAE-PAS-PAW",
					"2DW-4DN-ADE-3DS-6DE-KDS-7DW-8CN-2SS-4SW-ASN-7SE-KHN-AHE-5SS-7HW-8SS-9SW-TSN-3SE-QHN-2HE-7CS-5HW-THN-JHE-JSS-3HW-5DS-8DW-6SN-2CE-9HN-6HE-QCS-5CW-8HN-3CE-9DS-TDW-4HN-4CE-JDS-9CW-KCN-JCE-KSS-ACW-QSS-QDW-TCN-6CE" },
			new String[] {
					"W",
					"L",
					"NSWNWENSWENSESEESWNWWSWSNSEWWENEEWNNSSWEENWWENSSESNN",
					"PAW-1CN-PAE-2DS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"2SE-9SS-6SW-4SN-QHS-AHW-6HN-7HE-3HW-THN-2HE-KHS-QSS-5SW-8SN-7SE-2DS-8DW-KDN-4DE-7DN-3DE-ADS-6DW-QDS-9DW-2CN-7CE-3CS-4CW-QCN-ACE-3SE-TSS-6CW-KSN-ASN-JSE-5DS-TCW-JHN-5HE-TDS-4HW-5CN-JCE-KCS-JDW-9CS-9HW-8CN-8HE" },
			new String[] {
					"N",
					"E",
					"WNWENSSNNSENNSSWWWESWWENEEEWSEENWNNSESSSEWENEWSWNSNW",
					"1CN-PAE-1HS-PAW-2CN-PAE-3CS-PAW-3HN-PAE-4HS-PAW-PAN-PAE",
					"TDW-QDN-KDE-2DS-ADE-3DS-6DW-7HN-THN-6HE-4HS-3HW-9HN-2HE-JHS-8HW-8CS-4CW-ACN-5CE-KCN-QCE-JCS-2CW-6SN-3SE-QSS-8SW-AHS-4SW-JSN-5HE-KHS-4DW-KSN-QHE-7CS-TSW-TCN-7DE-9CN-7SE-9SS-ASW-6CN-5SE-2SS-9DW-3CN-JDE-8DS-5DW" },
			new String[] {
					"E",
					"A",
					"NSEWNESENSSNNNWSSWWSWWWSEEWNSNESEWWENEENWNEWEWESNSNS",
					"1HE-PAS-PAW-X1N-PAE-2HS-PAW-3CN-PAE-3DS-PAW-3NN-PAE-PAS-PAW",
					"AHE-4HS-2HW-3HN-ADE-4DS-7DW-2DN-KDE-5DS-3DW-2SN-8HE-7HS-9HW-QHN-2CN-4CE-QCS-5CW-JCS-6DW-6CN-7CE-8CS-JDW-KCN-9CE-ACN-6HE-3CS-THW-TCN-JHE-8DS-3SW-KSN-5SE-TSS-6SW-JSN-7SE-QSS-8SW-QDS-TDW-5HN-KHE-ASS-9DW-4SN-9SE" },
			new String[] {
					"S",
					"L",
					"SEWNSWWWSEWSSEWNESNNWESSEWEWEENNEWWESWSEWNNSNNSENNSN",
					"1CS-PAW-1SN-PAE-2NS-PAW-4SN-PAE-4NS-PAW-5DN-PAE-5SS-PAW-6NN-PAE-PAS-PAW",
					"THW-6HN-2HE-QHS-KSS-3SW-4SN-2SE-9SS-4CW-ASN-TSE-QSN-5DE-6SS-7CW-JSN-4HE-6DS-3HW-8SN-5HE-JDS-3DW-7SN-3CE-QDS-9DW-5SN-2DE-2CS-8CW-5CN-JCE-ACS-9CW-KCS-QCW-8DN-KDE-TCS-ADW-7DN-TDE-6CS-KHW-4DN-JHE-AHS-9HW-7HN-8HE" },
			new String[] {
					"W",
					"N",
					"NSSEWWSEEENSNNSSWEESNSWNESWWSWENSWNNSNNENEWEWNWEWWES",
					"PAW-1HN-PAE-2DS-PAW-2NN-PAE-3HS-PAW-4CN-PAE-4DS-PAW-4NN-PAE-5SS-PAW-5NN-PAE-6DS-PAW-6HN-PAE-PAS-PAW",
					"JCE-3CS-7CW-ACN-3SN-4SE-ASS-5SW-QHS-5HW-7HN-6HE-4HS-2HW-AHN-2SE-8SN-6SE-8HS-7SW-4CS-6CW-QCN-5CE-KHN-6DE-3DS-3HW-JHN-7DE-4DS-9HW-2DN-KDE-ADS-5DW-KCS-9SW-2CN-9CE-8DS-JDW-QDN-TSE-9DN-TCE-TDS-JSW-8CS-QSW-THN-KSE" },
			new String[] {
					"N",
					"A",
					"WWEEWNESEWWNWEEWNSWSNSNSSEEWEWSEWNWESSNSNWNNSENSENSN",
					"1SN-PAE-2DS-PAW-2SN-PAE-3NS-PAW-4SN-PAE-4NS-PAW-5HN-PAE-5SS-PAW-6NN-PAE-PAS-PAW",
					"5HW-AHN-7HE-6HS-9DN-ADE-6DS-7DW-3DE-8DS-4DW-JDN-5DN-2DE-KDS-6CW-KHS-3HW-9HN-2HE-QHS-8HW-7CN-4HE-QDS-2CW-KCN-8SE-TDS-THW-3SN-JHE-KSS-4SW-5SN-JSE-TSS-3CW-6SN-4CE-7SS-JCW-ASN-5CE-QSN-TCE-2SS-ACW-9SN-8CE-9CS-QCW" },
			new String[] {
					"E",
					"L",
					"ESWSWEESSWSWESEEEWWWNNWNNSWSSSNWNWNENSEEWEESEWNNSNNN",
					"PAE-1NS-PAW-2CN-PAE-2HS-PAW-3SN-PAE-4HS-PAW-5CN-PAE-5HS-PAW-6HN-PAE-PAS-PAW",
					"7DW-9DN-3DE-2DS-THN-AHE-3HS-7HW-ACE-3CS-6CW-6HN-QHN-JHE-4HS-2HW-8HN-2CE-KHS-9HW-ADS-6DW-TDN-4DE-JSS-8SW-ASN-7SE-KDN-5DE-6SS-8DW-QDN-7CE-5CS-JDW-KSN-2SE-9CS-3SW-QSN-4SE-TCS-4CW-TSN-5SE-QCS-JCW-9SN-8CE-5HS-KCW" },
			new String[] {
					"S",
					"N",
					"NSNENNEESWNWEENNSWENWNEWSSSEEWNNEWESSWSWSNSWWWESESWN",
					"1DS-1SW-PAN-PAE-1NS-PAW-3NN-PAE-PAS-PAW",
					"6SW-4SN-JSE-QSS-ADS-6DW-3DN-2DE-KDS-9DW-4DN-7DE-5DS-QDW-8DN-JDE-2SW-ASN-9SE-3SS-TDN-5CE-3CS-5HW-6HN-4HE-JHS-KHW-KSW-2CN-3HE-5SS-7SW-4CN-8CE-TSS-AHS-9HW-7HN-8HE-QHS-8SW-6CN-THE-2HS-JCW-7CN-9CE-TCS-KCW-QCN-ACE" },
			new String[] {
					"W",
					"E",
					"SEEESNEWNWWSSEENSSWNNNWEWSWEWEENSWSSWNENWSNNNWSEEWNS",
					"PAW-PAN-PAE-1NS-PAW-2HN-PAE-2SS-PAW-PAN-PAE",
					"QCW-7CN-5CE-KCS-ACS-9CW-TCN-3CE-2CS-JCW-2SN-4CE-4DN-2DE-6DS-7DW-4HW-7HN-AHE-8HS-8CE-6CS-8SW-KSN-KHN-3HE-THS-2HW-8DN-3DE-ADS-JDW-JHS-QHW-5SN-5HE-6SN-TSE-4SS-3SW-6HE-5DS-9HW-7SN-9DN-QDE-9SS-KDW-ASS-QSW-TDN-JSE" },
			new String[] {
					"N",
					"L",
					"WESESEWEWWNSNNNWEWEWESSSNSEWEEWNNSSESSSWWNNNWESNENWN",
					"1SN-PAE-2HS-PAW-2NN-PAE-4NS-PAW-5HN-PAE-7NS-PAW-PAN-PAE",
					"5CE-4CS-TCW-QCN-ACN-3CE-6CS-2CW-KDN-5DE-TDS-4DW-7HN-5HE-9HS-6HW-AHS-3HW-8HN-2HE-KHS-6DW-3DN-4HE-QHS-8DW-2DN-JHE-THS-2SW-4SN-7CE-KCS-8CW-5SN-9CE-ADS-3SW-6SN-7DE-QDS-JCW-TSN-9DE-JDS-7SW-QSN-8SE-9SS-KSW-ASN-JSE" },
			new String[] {
					"E",
					"N",
					"ENWEWSWWSESWEWNNWSENWENENSNEEWSSSNEWSNSWNESNWEWNSNSE",
					"PAE-1HS-PAW-1SN-PAE-2SS-PAW-4SN-PAE-PAS-PAW",
					"7DE-6DS-2DW-8DN-3SN-4SE-JSS-2SW-ADS-5DW-3DN-TDE-KSS-7SW-6SN-ASE-8SE-5SS-9SW-QSN-KHN-3HE-6HS-5HW-KDN-QDE-7CS-9DW-JDN-4HE-TCS-4CW-2HN-THE-AHS-JHW-QHS-6CW-9HN-2CE-8HS-8CW-3CN-5CE-QCS-KCW-TSN-ACE-4DN-JCE-7HS-9CW" },
			new String[] {
					"S",
					"E",
					"ENWWSWSWWWNENSNNEWNEEWESSESNNSENSWSNSWWENWNENESSEWES",
					"PAS-PAW-PAN-1SE-PAS-2CW-PAN-2DE-2HS-2SW-3HN-3SE-PAS-PAW-PAN",
					"9SS-QSW-3SN-2SE-4SW-5SN-8SE-TSS-THS-KHW-7HN-6HE-TDW-3DN-5DE-KDS-8HS-AHW-3HN-2CE-6DW-4DN-9DE-QDS-2HS-9HW-JHN-6SE-8DE-2DS-4CW-7DN-KSE-ASS-5CW-7SN-QHS-7CW-4HN-KCE-8CS-JCW-ACN-JSE-ADE-6CS-TCW-QCN-JDE-5HS-9CW-3CN" },
			new String[] {
					"W",
					"A",
					"WENWWEWWWESSEENNWSESSENNWNSSNWSWENNSNENEWSNNEWSWEESS",
					"PAW-1HN-PAE-3NS-PAW-4CN-PAE-4SS-PAW-5HN-PAE-6HS-PAW-PAN-PAE",
					"QSE-ASS-3SW-5SN-2HS-7HW-9HN-KHE-8HE-3HS-5HW-THN-6SN-2SE-KSS-8SW-6DS-KDW-ADN-2DE-QDN-7DE-8DS-5DW-JDN-TDE-9DS-6CW-4DN-3CE-QCS-TSW-3DN-7CE-KCS-2CW-4CN-JCE-6HS-5CW-JHS-TCW-AHN-JSE-QHN-7SE-9SS-9CW-4HN-ACE-4SS-8CW" },
			new String[] {
					"N",
					"L",
					"SSEEWNNSWWWNSNESEWNNSEWSNSNSNWSEEWWSWSENNWNEEWENSEEW",
					"PAN-PAE-1DS-PAW-1SN-PAE-2NS-PAW-PAN-PAE",
					"QCW-7CN-5CE-ACS-2CS-TCW-KCN-4CE-KDN-3DE-4DS-6DW-2DN-5DE-QDS-JDW-3CS-JCW-8CN-6SE-QHW-2HN-7HE-KHS-9CS-6CW-4HN-TDE-ADS-4SW-7DN-7SE-9DS-8SW-8DN-9SE-JSS-ASW-2SN-QSE-THW-3SN-8HE-JHS-6HS-9HW-TSN-AHE-KSE-3HS-5HW-5SN" },
			new String[] {
					"E",
					"N",
					"ENWEENENNWNWESSNNENESWWWSSEWSSEWENNWSSNWSWENSWENSSWE",
					"PAE-1DS-PAW-1NN-PAE-3NS-PAW-PAN-PAE",
					"5CE-2DS-KCW-3CN-4SW-TSN-ASE-3SS-ACE-3DS-4CW-7CN-2CE-9DS-JCW-QCN-6SN-5SE-QSS-2SW-4HS-JHW-AHN-2HE-TCN-6CE-7SS-7HW-9CN-8CE-JSS-3HW-9HN-6HE-KHS-8SW-KDS-TDW-4DN-6DE-ADS-JDW-7DN-8DE-QHS-QDW-THN-8HE-5HS-KSW-5DN-9SE" },
			new String[] {
					"S",
					"E",
					"EESNNWEWNESSSNESWENSWWSSSEWNENWWWEWESNSNSEENWSWWNENN",
					"2CS-PAW-2DN-PAE-2NS-PAW-3HN-PAE-4NS-PAW-5DN-PAE-6NS-PAW-PAN-PAE",
					"TDW-2DN-ADE-4DS-3CE-ACS-9CW-5CN-AHS-2HW-3HN-4HE-QHS-6HW-5HN-9HE-8SS-7SW-ASN-4SE-KSN-5SE-3SS-9SW-KHN-JHE-4CS-7HW-7DN-3DE-KDS-5DW-KCS-7CW-TCN-JCE-QCS-9DW-6CN-8CE-QDS-THW-JSN-6DE-JDS-8HW-6SN-2CE-8DS-TSW-2SN-QSE" },
			new String[] {
					"W",
					"A",
					"ENWEEENWWSEWWSSNEWWWSESEWWNWSNNESNSSSWSENNENESNNESWN",
					"1DW-PAN-1SE-2HS-3CW-3HN-5CE-PAS-6CW-PAN-PAE-PAS",
					"5HN-7HE-AHS-3HW-JCS-4CW-8CN-QCE-2CE-4HS-KCW-3CN-ADW-4DN-5DE-2DS-6DW-2HN-QDE-3DS-TDE-JDS-KDW-6HN-7DW-9HN-5CE-9DS-2SE-8SS-KSW-ASN-TSN-5SE-QSS-TCW-ACW-9SN-7CE-QHS-9CW-6SN-6CE-JHS-8DW-4SN-JSE-THS-KHW-3SN-7SE-8HS" },
			new String[] {
					"N",
					"N",
					"SWEENSWNWSSNNSWSENWEWNNNSNESSEEWWENWSWSNEWESNENSEEWW",
					"1DN-PAE-2NS-PAW-3CN-PAE-3NS-PAW-PAN-PAE",
					"7HW-THN-6HE-3HS-6DN-8DE-KDS-3DW-2DS-7DW-TDN-5DE-JDN-5CE-4DS-9DW-QDN-4CE-6SS-8HW-ADN-3SE-TSS-JHW-ACN-5SE-2CS-3CW-KCN-8SE-7CS-8CW-6CN-JSE-JCS-TCW-QCS-4SW-9CN-QSE-AHS-KHW-2SN-2HE-QHS-KSW-7SN-5HE-4HS-ASW-9SN-9HE" },
			new String[] {
					"E",
					"E",
					"SSSSEEWWESENNSEEWEWSEWWNNWENSNWNSSSWENWNWENNSNWEENSW",
					"PAE-1HS-PAW-1SN-PAE-PAS-X1W-PAN-2CE-PAS-PAW-PAN",
					"2DS-ADW-QDN-4DE-8CW-KCN-6CE-2CS-2SN-4SE-7SS-9SW-9CW-ACN-7CE-4CS-5SN-JSE-KSS-ASW-3SW-QSN-TSE-8DS-6SN-TCE-JCS-5DW-4HS-6HW-KHN-2HE-KDN-3DE-8HS-7DW-8SN-6DE-9HS-TDW-3HN-QHE-THS-JHW-QCE-3CS-JDW-5HN-9DE-5CS-AHW-7HN" },
			new String[] {
					"S",
					"A",
					"WEWWNWNNSESEEWWSEENWWSNNSEEESEWWSNSSENNWWENEWSNNSSNS",
					"1NS-PAW-2CN-PAE-2NS-PAW-3DN-PAE-3NS-PAW-PAN-PAE",
					"8DW-7DN-5DE-TDS-ASS-2SW-5SN-6SE-QSS-3SW-9SN-4SE-8SS-7SW-KSN-5HE-TSN-6DE-JSS-7CW-4HS-7HW-9HN-QHE-ADE-4DS-2DW-JDN-ACE-TCS-2CW-6CN-JCE-QCS-4CW-8CN-8HS-6HW-AHN-2HE-KHN-3HE-JHS-5CW-QDN-3CE-KDS-3DW-THS-9DW-9CN-KCE" },
			new String[] {
					"W",
					"L",
					"SSSEENSNWENSWENNEENWEWWSNWSEESEWWWSNSSNENENWWSSWNNEW",
					"1DW-PAN-PAE-X1S-PAW-2SN-PAE-2NS-PAW-3NN-PAE-PAS-PAW",
					"JDW-3DN-6DE-QDS-2CS-ACW-7CN-5CE-7HW-AHN-3HE-2HS-JHN-4HE-5HS-8HW-QCN-6CE-3CS-TCW-9CN-JCE-KCS-7SW-8CS-6SW-4DN-2DE-4CS-8DW-7DN-5DE-KHS-9HW-KDN-6HE-QHS-TSW-3SN-9DE-THS-TDW-5SN-2SE-9SS-ASW-QSN-KSE-ADW-JSN-4SE-8SS" },
			new String[] {
					"N",
					"E",
					"EWESSSNNWWNWSNWNWNNSNNSSWWNEEESEWEEEEWESSEWNESSNNWWS",
					"PAN-4HE-PAS-PAW-PAN",
					"5CS-TCW-QCN-2CE-JSN-4SE-ASS-5SW-ACS-3CW-8CN-4CE-6CS-JCW-9CN-4HE-3HE-6HS-8HW-2HN-ADW-7DN-JHE-8DS-7SE-2SS-QSW-6SN-KHW-TSN-AHE-9SS-QHE-8SS-KSW-TDN-THE-3SS-KCW-9DN-9HE-7CS-KDW-6DN-7HE-QDS-5DW-4DN-5HE-JDS-3DW-2DN" },
			new String[] {
					"E",
					"A",
					"ENSNEEWESNWWNENWSNWWNSEWSSWWEESSNNSNWNWWENWESESEESSN",
					"PAE-1DS-PAW-1HN-PAE-1SS-PAW-3NN-PAE-PAS-PAW",
					"7CE-4CS-QCW-ACN-3DN-2DE-ADS-7DW-6HS-AHW-8HN-5HE-KCW-3CN-2CE-TCS-2HW-9HN-4HE-7HS-9DN-JDE-KDS-4DW-THS-3HW-JHN-3SE-KHN-6SE-5DS-QHW-JCN-6CE-TDS-8CW-ASN-8SE-7SS-2SW-4SN-TSE-KSS-5SW-QSS-QDW-5CN-JSE-9SS-8DW-6DN-9CE" },
			new String[] {
					"S",
					"L",
					"EEEWSWNEWWSWWWNNNWNSWWENSNSSSESSESNSNSENWWWEEENENENS",
					"2CS-X1W-3DN-PAE-3HS-PAW-3SN-PAE-4DS-PAW-4HN-PAE-4SS-PAW-4NN-PAE-5DS-PAW-5SN-PAE-6HS-PAW-PAN-PAE",
					"TDW-3DN-JDE-KDS-2HS-7CW-QHN-AHE-6SE-ASS-3SW-2SN-KHS-5CW-THN-5HE-JHS-4SW-8CN-8HE-8DS-2DW-ADN-4CE-QDN-2CE-6CS-6DW-KSN-7SE-QCS-5SW-JSN-QSE-9HS-ACW-7HS-KCW-9SN-TSE-6HS-JCW-7DN-8SE-4HS-TCW-5DN-9CE-3HS-9DW-4DN-3CE" },
			new String[] {
					"W",
					"N",
					"EEWWESSENEWEENENSWNWWENWSWEWNNWNSSNNSWSSEESNESNWNSWS",
					"1DW-PAN-1NE-2SS-PAW-PAN-3CE-X1S-PAW-3SN-PAE-PAS-PAW",
					"4CW-TCN-KCE-7CS-2HE-AHS-3HW-4HN-8CS-5CW-6SN-6CE-JSN-3SE-2SS-KSW-TSW-9SN-4SE-QSS-ASS-6DW-2DN-7SE-8HS-KHW-5HN-2CE-QCW-4DN-3CE-5SS-QHS-6HW-7HN-ACE-9HS-8DW-THN-JCE-JHN-3DE-5DS-9DW-7DN-TDE-KDS-ADW-QDW-JDN-9CE-8SS" },
			new String[] {
					"N",
					"A",
					"WNNNENEENESWNESNWWENNEESWWSNNEWWWNSSEWSESWWENWSSSSES",
					"PAN-PAE-1SS-PAW-PAN-PAE",
					"ADW-4DN-7DE-3DS-KDW-8DN-2DE-QDS-6DW-9DN-TDE-3SS-QCS-KCW-ACN-8CE-9HN-5HE-2HS-KHW-2CW-3CN-6CE-9SS-ASS-5SW-7SN-6SE-QSS-4SW-4CN-KSE-JCE-TSS-5DW-5CN-AHS-6HW-3HN-QHE-JSS-8SW-7CN-2SE-JHS-8HW-4HN-9CE-THS-7HW-TCN-JDE" },
			new String[] {
					"E",
					"L",
					"WSWNNWESEWSSNEWWSNSESEWSESEENEWWENNNNEWWWSSNESNWSENN",
					"PAE-1DS-PAW-1HN-PAE-1SS-PAW-3SN-PAE-6SS-PAW-PAN-PAE",
					"4CW-5CN-TCE-QCS-4SS-2SW-ASN-7SE-6DN-8DE-QDS-3DW-5DS-4DW-6SN-2DE-4HN-8HE-5SS-7HW-7DS-JDW-9SN-TDE-KSN-QSE-8SS-3SW-6CN-8CE-KCS-2CW-JSS-TSW-9HN-KDE-ADS-6HW-THN-2HE-9DS-7CW-JHN-3HE-3CS-JCW-ACN-5HE-QHN-KHE-9CS-AHW" },
			new String[] {
					"S",
					"N",
					"WSEEWNNSWNSSEESSEEWWSWNNEEWWNWSSWEEWSNSNWENNNNESENWS",
					"PAS-PAW-PAN-1DE-PAS-PAW-1SN-PAE-3NS-PAW-PAN-PAE",
					"7DW-JDN-KDE-3DS-4CE-3CS-2CW-7CN-2SN-4SE-ASS-3SW-TSS-KSW-5SN-9SE-8DW-QDN-ADE-4DS-2DE-9DS-TDW-8CN-2HW-KHN-9HE-6HS-QSN-JSE-9CS-6CW-8SN-5DE-QCS-TCW-7SN-6DE-KCS-3HW-6SN-5CE-7HS-5HW-4HN-THE-QHS-8HW-AHS-JHW-JCN-ACE" },
			new String[] {
					"W",
					"E",
					"ESWWNNSNSSSWNNEEWNEESSNNSNEWEWNEEWENWSWWSSESWNENWEWS",
					"1HW-PAN-2HE-X1S-PAW-3DN-PAE-4CS-PAW-4NN-PAE-PAS-PAW",
					"2HE-KHS-AHW-6HN-5HW-JHN-4HE-3SS-2DN-7DE-KDS-5DW-QCS-4CW-6CN-2CE-JCS-5CW-7CN-3DE-3CS-KCW-ACN-7HE-9CN-4DE-TCS-7SW-8CS-2SW-8SN-8DE-9DS-JSW-ADN-8HE-QDN-THE-TDS-3HW-JDN-5SE-4SS-9HW-6DN-9SE-6SS-QHW-TSN-QSE-ASS-KSW" },
			new String[] {
					"N",
					"L",
					"NESWSNWSWSNWSWWNSNNWNNSWENESWSSWEWEENESSSNNENEWEEEEW",
					"PAN-1SE-PAS-1NW-2DN-2HE-3DS-PAW-PAN-PAE",
					"3CE-ACS-8CW-2CN-JDS-QDW-ADN-KDE-QCN-2HE-4CS-KCW-ASW-4SN-KSE-2SS-9SW-5SN-6SE-3SS-3DW-6DN-8HE-5DS-TDN-8SE-3HS-2DW-9DN-THE-5HS-8DW-7DN-TSE-6HS-4HW-7CN-JSE-JCS-5CW-9CS-TCW-4DN-JHE-QHN-KHE-AHS-7HW-6CS-9HW-7SN-QSE" },
			new String[] {
					"E",
					"N",
					"NNSNWSSSNNSNNWESWEESNSESSWSEEEEWNNEWWSWWNEWEWSEENWWN",
					"PAE-PAS-1SW-2CN-2SE-3CS-4SW-5CN-5SE-X1S-PAW-6CN-PAE-PAS-PAW",
					"TSE-8SS-QSW-ASN-9DN-7DE-4DS-ADW-5DW-8HN-3DE-8DS-4CS-6CW-ACN-6DE-KCN-JDE-7CS-2DW-3SN-4SE-8CS-7SW-KDS-2SW-9HN-6SE-QDS-5SW-JSN-9SE-QCS-AHW-JCN-THE-9CS-QHW-TCN-6HE-5CN-5HE-TDS-JHW-3CN-4HE-KHS-7HW-2CN-3HE-2HS-KSW" },
			new String[] {
					"S",
					"E",
					"WWWSWSEENSSENNEWWNWSENNESNWSSNSENWEENWSWWWSNESEENENS",
					"1CS-PAW-3NN-PAE-PAS-PAW",
					"TSE-5SS-2SW-JSN-ACN-8CE-5CS-6CW-TCN-KCE-7CS-2CW-9DE-8DS-4DW-TDN-2DN-3DE-KDS-5DW-8SS-3SW-KSN-7SE-ADN-QDE-3HS-7DW-JDN-9CE-4HS-3CW-6DN-7HE-6HS-4CW-QHN-JHE-AHS-KHW-QCS-9HW-8HN-THE-JCS-2HW-5HN-QSE-ASS-4SW-6SN-9SE" },
			new String[] {
					"W",
					"A",
					"ENEENWSSSNNEEWWNNWNESWNSSSWESNSNWWWENSENEWSWNEWWEESS",
					"PAW-PAN-1CE-X1S-PAW-1DN-1SE-3NS-PAW-PAN-PAE",
					"THW-5HN-3HE-KHS-9DS-TDW-JDN-8DE-4DN-2CE-QDS-2DW-KDS-3DW-5DN-4CE-ADS-6DW-7DN-5CE-TCS-7CW-3CN-KCE-8SE-ASS-6SW-2SN-9CS-2HW-6CN-ACE-QSE-KSS-4SW-7SN-8CS-8HW-JCN-JHE-QCN-3SE-5SS-9HW-QHN-AHE-6HS-TSW-JSE-4HS-9SW-7HN" },
			new String[] {
					"N",
					"L",
					"WWWWNNEWNSSEESNENSESENWESSWENENSESWSSSWWNWENNEWWNENS",
					"PAN-PAE-2NS-PAW-3HN-PAE-3NS-PAW-PAN-PAE",
					"5CW-6CN-KCE-JCS-3HE-KHS-AHW-4HN-2CW-7CN-ACE-QCS-5HE-QHS-2HW-6HN-ASS-4SW-3SN-5SE-JHS-THW-TCN-8HE-9HS-3CW-3DN-7DE-7HS-JDW-5DN-4DE-ADS-4CW-TDN-9DE-KDS-9CW-KSN-QDE-8DS-TSW-JSN-8CE-6DS-9SW-7SN-QSE-2DS-2SW-6SN-8SE" },
			new String[] {
					"E",
					"N",
					"WNWNWSNEESNESWWSESSENNSWSEESSNWWENESNENWWWSNEWENSEWN",
					"1CE-1NS-PAW-2CN-PAE-2DS-PAW-3NN-PAE-PAS-PAW",
					"2CW-3CN-9CE-JCS-3HS-7HW-QHN-KHE-TCE-7CS-4CW-QCN-9DN-ADE-4DS-2DW-KCE-ACS-6CW-5CN-6DS-QDW-TDN-8DE-6HW-5HN-2HE-JHS-KDS-3DW-6SN-5DE-JDS-2SW-TSN-8HE-7DS-3SW-9HN-THE-4HS-KSW-AHN-QSE-8CN-9SE-JSS-8SW-ASN-7SE-5SS-4SW" },
			new String[] {
					"S",
					"E",
					"EEEEWNSSSNWNWSEEWWSENNWNNWNESEWWEWNNNSWWNSENSSWESESS",
					"PAS-1NW-PAN-PAE-2SS-X1W-PAN-2NE-PAS-PAW-PAN",
					"QHN-3HE-4HS-6HW-KDN-3DE-2DS-ADW-AHW-2HN-5HE-KHS-7HW-THN-8HE-4SS-JHN-2CE-7SS-9HW-JCN-3CE-8CS-QCW-2SW-6SN-TSE-JSS-ASS-9SW-3SN-5SE-KSS-5DW-7CN-QSE-8SS-6CW-KCN-4CE-7DS-JDW-QDN-4DE-TDN-8DE-TCS-6DW-9DN-5CE-9CS-ACW" },
			new String[] {
					"W",
					"A",
					"WWEWWSNSESENENSSEENWWSNSNNWSEWNNWSWESSNEWNEWNSENWSEE",
					"PAW-1NN-PAE-2CS-PAW-2DN-2SE-2NS-PAW-3NN-PAE-PAS-PAW",
					"5SE-QSS-3SW-4SN-3HS-8HW-AHN-4HE-6HN-JHE-KHS-2HW-QHS-5HW-7HN-6DE-QDS-9DW-2DN-5DE-TDS-8DW-7DN-4CE-3DS-6CW-ADN-TCE-KDN-2SE-4DS-2CW-JDN-QCE-7CS-3CW-8CN-ACE-9CS-5CW-ASE-8SS-6SW-7SN-KSE-9HS-JSW-TSN-9SE-JCS-THW-KCN" },
			new String[] {
					"N",
					"N",
					"EEESWNNWNSWWENNEWENSSNEESNSSNWSNWWWSSEWEWENWSESSNNWE",
					"PAN-1DE-PAS-1HW-PAN-1SE-PAS-2CW-PAN-2NE-PAS-3NW-PAN-PAE-PAS",
					"3HS-5HW-7HN-KHE-2CE-5CS-QCW-7CN-KCW-8CN-3CE-JCS-6CW-TCN-ACE-8DS-4CE-7SS-9CW-4HN-5DW-ADN-4DE-9DS-QSN-2SE-9SS-KSW-AHW-2DN-6DE-2HS-3SW-5SN-ASE-TSS-4SE-6HS-6SW-JSN-TDN-QDE-KDS-THW-QHS-9HW-7DN-JDE-JHS-8HW-3DN-8SE" },
			new String[] {
					"E",
					"E",
					"EENESWSESSSSNNWWESWNNESWSNNNWWNEWNSNSEEESNWWNEWEEWSW",
					"PAE-1CS-1SW-X1N-3SE-3NS-PAW-PAN-PAE",
					"5SW-4SN-TSE-KSS-6CS-7CW-ACN-5CE-4CN-2CE-KCS-7DW-QCS-4HW-7SN-3CE-JCS-5HW-2HN-9CE-TCS-8HW-3HN-7HE-8CS-3DW-6HN-5DE-KDS-4DW-2DN-TDE-JDS-QDW-ADN-2SE-9DN-8SE-6DS-6SW-8DN-JSE-3SS-9SW-JHN-AHE-QHS-ASW-KHE-THS-QSW-9HN" },
			new String[] {
					"S",
					"A",
					"NEWNENSWSSSESSEEWWSSNENENNSWEESWWEWENENSWNSNWNWWWNSE",
					"PAS-PAW-1NN-PAE-2CS-PAW-2SN-PAE-3CS-PAW-3NN-PAE-PAS-PAW",
					"3DE-2DS-6DW-9DN-7CN-3CE-TCS-9CW-7DS-5DW-KDN-4DE-5CN-6CE-JCS-4CW-ACS-3SW-2CN-KCE-QCS-7SW-4SN-4HE-8CS-9SW-6SN-5HE-2SS-TSW-QSN-ASE-JHE-2HS-3HW-QHN-8SN-9HE-KSS-JSW-5SS-7HW-JDN-KHE-8DS-THW-ADN-QDE-AHN-TDE-6HS-8HW" },
			new String[] {
					"W",
					"L",
					"SNENSEENEEWSSSEESWEWNSSWESENWSWWNNESWSNWNWNNENEWWNWS",
					"PAW-PAN-PAE-2NS-PAW-3CN-PAE-3DS-PAW-3SN-PAE-3NS-PAW-PAN-PAE",
					"6DW-9DN-KDE-ADS-2CS-QCW-3CN-4CE-QDW-5CN-3DE-2DS-8DW-9CN-4DE-JDS-TDS-7HW-3SN-7DE-5DS-2SW-5SN-7CE-ACS-4SW-6SN-8CE-KHS-QHW-3HN-2HE-JHS-4HW-8HN-THE-KCS-6HW-8SN-TCE-5HS-TSW-AHN-7SE-9HN-JCE-6CS-JSW-QSN-9SE-ASS-KSW" },
			new String[] {
					"N",
					"E",
					"EWENWSSNEWNSEWESEENENWWEWSWWNNSNEENSSNSWWSSEWENWSSNN",
					"1HN-PAE-4NS-PAW-5DN-PAE-6NS-PAW-PAN-PAE",
					"3SW-ASN-8SE-4SS-KSN-6SE-5SS-2SW-9SN-9HE-QSS-7SW-JSS-TSW-7DN-8HE-AHS-3HW-4HN-4CE-QHS-2HW-5HN-3DE-JHS-2DW-7HN-5DE-6HS-3CW-KHN-2CE-THN-TCE-4DS-6CW-5CN-ACE-7CS-JCW-6DE-ADS-TDW-9DN-8CS-JDW-QCN-8DE-9CN-QDE-KCS-KDW" },
			new String[] {
					"E",
					"A",
					"EWNEESSSNSNSWSNNEWWEENNSSEWNEENSSWWSNWWEEWWNESENNSWW",
					"PAE-1CS-X1W-1DN-1SE-1NS-2CW-PAN-2NE-PAS-3HW-PAN-3NE-PAS-PAW-PAN",
					"KDS-6DW-4DN-ADE-5HE-7HS-KHW-3HN-ASW-6SN-2SE-8SS-AHW-6HN-4HE-8HS-KSW-TSN-3SE-QSS-4SW-JSN-7SE-7CS-JDN-5DE-2DS-7DW-3DN-9DE-QDS-2HW-8CS-ACW-4CN-2CE-5SW-TCN-9SE-9CS-5CE-JCS-3CW-QCN-TDN-8DE-KCS-THW-QHN-6CE-JHS-9HW" },
			new String[] {
					"S",
					"L",
					"NWSWSEWSEEESSSNENNESNWESSNNSWWEWSNNWNSWEENWNEWESEWNW",
					"1CS-1HW-PAN-PAE-2DS-PAW-3NN-PAE-PAS-PAW",
					"6HE-3HS-4HW-9HN-3DN-7DE-KDS-TDW-2DS-8SW-ADN-4DE-5DN-JDE-QDS-5HW-8DS-3CW-9DN-2SE-6DN-3SE-4CS-5SW-2HN-7CE-KHS-AHW-ASW-4SN-7SE-TSS-QSW-KSN-9SE-6CS-2CN-TCE-ACS-5CW-KCS-8CW-6SN-JCE-8HS-7HW-THN-QCE-QHN-JSE-9CS-JHW" },
			new String[] {
					"W",
					"N",
					"NNEWSWSNWWSSWWESEENEWWSSSSEWSWEEENNNNWWNSNESSNWNEEEN",
					"2CW-PAN-2DE-X1S-3CW-PAN-PAE-X1S-PAW-3SN-PAE-3NS-PAW-PAN-PAE",
					"JCW-2CN-4CE-KCS-4HS-KHW-9HN-7HE-ACW-3CN-2HE-6CS-TDW-7DN-6DE-ADS-KDS-2DW-2SN-3DE-QDS-9DW-4SN-5DE-JDS-5CW-8SN-8DE-4DS-3HW-THN-6HE-QCS-7CW-9CN-8HE-3SS-9SW-ASN-5SE-JHN-JSE-6SS-AHW-TCW-TSN-QSE-8CS-5HW-QHN-KSE-7SS" },
			new String[] {
					"N",
					"A",
					"WESNENNESWNSSESNWSSWSWENSWENNWEWWESWNNSNEENWESWESNWE",
					"PAN-PAE-1NS-PAW-2CN-PAE-2DS-PAW-3NN-PAE-PAS-PAW",
					"5HW-3HN-9HE-THS-AHS-7HW-4HN-6HE-3DS-5DW-QDN-2DE-5CN-3CE-ACS-JCW-4CS-2CW-QCN-6CE-QHN-2HE-6DS-8HW-KHN-3SE-7DS-JHW-8CN-9CE-TCS-8DW-KCS-6SW-7CN-4SE-8SS-KSW-2SN-7SE-ADW-4DN-JDE-9DS-9SW-5SN-TSE-JSS-KDS-TDW-QSN-ASE" },
			new String[] {
					"E",
					"L",
					"NWSWEWEWSEENEESESSNWNWSSWSNENNNWEWSWNNSWSEEWWENENSSN",
					"PAE-1DS-PAW-1HN-PAE-5DS-PAW-6DN-PAE-PAS-PAW",
					"2SW-ASN-5SE-3SS-9DN-4DE-JDS-KDW-6SW-9SN-TSE-KSS-ADS-8DW-7DN-2DE-QDS-TDW-2CN-6CE-AHS-7HW-2HN-8HE-THS-JHW-KHN-3HE-QHN-4SE-4CS-9HW-6HN-8CE-TCS-3CW-5HN-8SE-6DS-7SW-5DS-9CW-4HN-ACE-3DS-7CW-JSN-QCE-QSS-5CW-KCN-JCE" },
			new String[] {
					"S",
					"N",
					"SSSSNNEEWNSNNSSWWWWNEWWSSEWEEESWNEWWWSENESENSENNNWEN",
					"PAS-PAW-1SN-PAE-1NS-PAW-2CN-PAE-3CS-PAW-3SN-PAE-4SS-PAW-PAN-PAE",
					"ADE-2DS-7DW-8DN-9DE-QDS-4DW-8HN-4SS-QSW-ASN-5SE-JSN-KSE-7SS-TCW-AHE-6HS-2HW-2SN-TSN-3SE-3DS-5DW-9SN-8SE-2CS-6DW-ACN-8CE-3CS-7HW-KCN-9CE-4CS-THW-JCN-3HE-5CS-JDW-6CN-4HE-QCS-TDW-KDS-QHW-6SN-9HE-7CN-5HE-KHS-JHW" },
			new String[] {
					"W",
					"E",
					"ENSESWSWNNEEEESSNWNNWENNNSSESNWESEWSWSESWNWWWEWNWENS",
					"PAW-PAN-1NE-2HS-2SW-3DN-PAE-3NS-PAW-PAN-PAE",
					"6SW-4SN-QSE-ASS-2SS-3SW-TSN-8SE-5DN-TDE-ADS-9DW-3DS-6DW-7DN-2DE-8DN-7HE-4DS-9CW-JDN-2CE-4CS-7CW-QDN-5CE-6CS-5SW-KDN-3HE-2HS-7SW-5HN-AHE-4HS-6HW-ACE-8CS-THW-3CN-KCE-8HS-QHW-TCN-QCE-JHS-9SW-JCN-9HE-KHS-JSW-KSN" },
			new String[] {
					"N",
					"L",
					"WSSWNWEESSEESWSSWSWNNWNWESNWNENEEWNSNNWESEENEWNESNWS",
					"2HN-PAE-2NS-PAW-4CN-PAE-5CS-PAW-5SN-PAE-5NS-PAW-PAN-PAE",
					"5DW-8DN-KDE-ADS-JHS-AHW-2HN-5HE-QDW-9DN-8CE-3DS-KSW-6SN-2SE-ASS-3SS-8SW-QSN-4SE-KHN-7HE-3CS-3HW-QHN-8HE-4CS-9HW-THN-9CE-TCS-2CW-4HN-5SE-JCS-5CW-6HN-7SE-4DS-7CW-9SN-TSE-JSS-2DW-ACS-7DW-6CN-QCE-6DS-TDW-JDN-KCE" },
			new String[] {
					"E",
					"N",
					"EWSSNWESWSNESWNNSNWWWSNSNEWSEWWSEWEESNSNNENEWSWEENEN",
					"1SE-X1S-PAW-2SN-PAE-4HS-PAW-6NN-PAE-PAS-PAW",
					"JSE-8SS-9SW-QSN-4DN-ADE-5DS-7DW-JHE-3HS-6HW-KHN-3DN-6SE-QDS-2DW-AHS-2HW-2SN-THE-QHS-5HW-3SN-4HE-TDS-8DW-KDN-2CE-JDN-8HE-4CS-9DW-6DN-4SE-5CS-3CW-ASN-TSE-7HS-7SW-QCN-8CE-9CS-7CW-6CN-KCE-ACS-TCW-JCS-9HW-5SN-KSE" },
			new String[] {
					"S",
					"E",
					"NSSSWESSSENNWWNEWENWSNENEWSWNESWWWNNSSWWEWSSNENENEEE",
					"3CS-PAW-4CN-4SE-PAS-6NW-PAN-PAE-PAS",
					"QCN-7CE-3CS-ACW-2SW-7SN-QSE-6SS-5HE-KHS-AHW-4HN-2DW-3DN-KDE-9DS-ASE-5SS-4SW-9SN-KSE-2HS-6CW-JSN-TSE-6HS-3HW-7DN-3SE-4CS-5DW-2CN-8SE-5CS-7HW-THN-4DE-8CS-ADW-TDN-9HW-JHN-6DE-QHS-TCS-8DW-KCN-JCE-QDN-JDE-9CS-8HW" },
			new String[] {
					"W",
					"A",
					"SWNEENEWNWSSSWWNSSWEWWWEEEESSWSWESWENSNNENNWNSSENENN",
					"PAW-1SN-PAE-2CS-PAW-2SN-PAE-3HS-PAW-4NN-PAE-5DS-PAW-6CN-PAE-PAS-PAW",
					"6SW-ASN-3SE-8SS-4CN-5CE-ACS-3CW-KCS-9CW-7CN-6CE-QCS-JCW-TCN-8CE-3HS-5HW-QHN-2HE-KSN-TSE-9SS-7DW-2SN-QSE-2CS-2DW-4HS-7HW-AHN-8HE-JSN-8DE-5DS-THW-7SN-QDE-6DS-3DW-5SN-KDE-6HS-9DW-4SN-JHE-9HS-TDW-4DN-ADE-KHS-JDW" },
			new String[] {
					"N",
					"L",
					"ENNESSNWSSWNWSSWWSSWENWENESEEWSWSNENNENSEEEWWNNNEWSW",
					"1CN-PAE-1DS-PAW-1HN-PAE-PAS-PAW",
					"5CE-JCS-ACW-3CN-7HW-JHN-KHE-2HS-5SE-2SS-QSW-8SN-5HW-QHN-4HE-6HS-KCN-2CE-6CS-9CW-4CN-3SE-TCS-QCW-5DW-KDN-ADE-2DS-4SE-KSS-ASW-9SN-4DW-TDN-QDE-3DS-3HE-8HS-8DW-9HN-AHN-THE-7CS-6SW-8CN-9DE-6DS-JDW-TSN-JSE-7DS-7SW" },
			new String[] {
					"E",
					"N",
					"EWNNESWENWSNSEEEWWSWNNEWWNWENSSSWSNWWESSENNSESSENEWN",
					"PAE-1HS-PAW-1SN-PAE-2SS-PAW-4SN-PAE-PAS-PAW",
					"2CE-QCS-3CW-4CN-7DS-QDW-ADN-4DE-9DN-2DE-2SS-6DW-6SS-KSW-ASN-7SE-TDN-JDE-8SS-5DW-ACS-JCW-5CN-6CE-7CS-8CW-KCN-9CE-TCN-3SE-9SS-8DW-AHS-2HW-4HN-3HE-5HS-8HW-THN-KHE-3DE-6HS-KDW-4SN-5SN-TSE-7HS-JHW-QSE-9HS-QHW-JSN" },
			new String[] {
					"S",
					"E",
					"EEESSEWWENWSENWWSSNEWNWNNSSSEWNWEESNNNSNNSWWESNESWEW",
					"1CS-PAW-1DN-PAE-1HS-PAW-4HN-PAE-PAS-PAW",
					"8CW-JCN-ACE-5CS-8DE-5DS-4DW-TDN-6HN-8HE-AHS-7HW-2HS-5HW-JHN-4HE-QHN-9HE-3HS-6SW-2DN-2CE-ADS-3DW-KCS-9CW-2SN-3CE-6DS-9DW-KDN-4CE-QDN-7SE-4SS-JDW-7DN-7CE-8SS-5SW-3SN-TSE-JSS-QSW-QCW-KHN-TCE-6CS-9SN-KSE-THS-ASW" },
			new String[] {
					"W",
					"A",
					"WEEWNSNNEEEWSEWESNESWESSWNSSNENNEEWWSWSWNSWWENSNWNSN",
					"PAW-PAN-PAE-1NS-PAW-2HN-PAE-2SS-PAW-3NN-PAE-4SS-PAW-PAN-PAE",
					"JHW-4HN-5HE-QHS-4SS-5SW-QSN-7SE-3SN-3CE-KSS-2SW-9SS-JSW-ASN-4CE-TSN-8HE-7CS-6SW-6HN-9HE-AHS-THW-QDS-KDW-ADN-7DE-7HN-2DE-2HS-KHW-3DW-6DN-TDE-JDS-5DS-9DW-8SN-4DE-9CN-QCE-ACS-KCW-8DS-5CW-8CN-JCE-3HS-2CW-6CN-TCE" },
			new String[] {
					"N",
					"N",
					"NNSNSNWSSNWSWESNESESWWENSWNEWWESNWWESNWEENSEEEENWWSN",
					"PAN-PAE-1NS-2HW-3NN-PAE-PAS-PAW",
					"THW-2HN-3HE-QHS-4CS-QCW-2CN-7SE-ADW-4DN-7DE-3DS-TDW-QDN-2DE-6DS-3CN-6HE-KCS-8CW-TCS-ACW-5CN-JHE-AHW-8HN-2SE-7HS-9DW-4SN-5DE-KDS-KSS-JSW-TSN-3SE-5SS-QSW-ASN-6SE-KHN-8SE-6CS-4HW-JCN-JDE-9CS-9HW-7CN-9SE-8DS-5HW" },
			new String[] {
					"E",
					"E",
					"ENESENSNSSWNSWNWWSWSNEWEEWNNEEWESNEWNSSNSWWEWSNNEWSE",
					"PAE-1CS-1DW-1HN-1NE-2CS-2DW-3CN-3DE-3HS-PAW-4CN-5DE-PAS-PAW-PAN",
					"7CN-2CE-ACS-QCW-AHS-6HW-3HN-4HE-KHS-JHW-2HN-5HE-8HS-JDW-9HN-7HE-2DW-9DN-TDE-8DS-KDE-6DS-4DW-3DN-4CE-5CS-7DW-3CN-4SW-2SN-JSE-KSS-8CS-5DW-9CN-6CE-5SW-9SN-ASE-3SS-THE-TCS-ADW-QHN-QSW-TSN-6SE-8SS-7SW-KCN-QDE-JCS" },
			new String[] {
					"S",
					"A",
					"ESWWSNENNNSWWWNNWSWESWNESWSWEEEENNNSESWESWSEENSWENNS",
					"1CS-1NW-PAN-2DE-PAS-2HW-PAN-PAE-PAS",
					"JCN-2CE-3CS-ACW-KCW-7CN-8CE-6CS-4CW-9CN-4HE-QCS-5HE-2HS-AHW-8HN-5CW-TCN-8DE-3SS-THN-QHE-KHS-3HW-KDS-ADW-3DN-QDE-2DW-4DN-6HE-6DS-2SE-5SS-TSW-QSN-9HN-7HE-JHS-7DW-ASS-4SW-8SN-6SE-9SS-TDW-KSN-JSE-JDN-7SE-9DS-5DW" },
			new String[] {
					"W",
					"L",
					"EENSNNSNSWSESESWESNWWWNWNNWNWNEEEESSEWSNWSNEWWESWESN",
					"PAW-1DN-PAE-2CS-PAW-2NN-PAE-4NS-PAW-5HN-PAE-6NS-PAW-PAN-PAE",
					"6HE-THS-KHW-3HN-TDW-ADN-5DE-3DS-4CN-2CE-QCS-JCW-4SS-7SW-ASN-6SE-9CN-KCE-ACS-8DW-5CS-4DW-7CN-3CE-5HN-7HE-JHS-4HW-AHS-2HW-2SN-8HE-TCS-3SW-6CN-2DE-8CS-8SW-5SN-QHE-KSS-JSW-7DN-9SE-6DS-9DW-JDN-9HE-KDN-QSE-TSS-QDW" },
			new String[] {
					"N",
					"E",
					"EENWEWNSSSWSSNWESENNNWEENESNNNESWNSWSESWNWNEWWSWSEWE",
					"PAN-1NE-X1S-2SW-PAN-PAE-3HS-3SW-4HN-PAE-PAS-PAW",
					"TDW-KDN-ADE-5DS-KHE-AHS-8HW-3HN-QHS-JHW-4HN-6HE-ACS-5CW-4CN-2CE-KCS-7CW-8CN-3CE-JCS-QCW-5HN-6CE-2DN-6DE-2HS-3DW-TCS-2SW-3SN-4DE-9CS-4SW-5SN-6SE-9SS-TSW-9HN-QSE-7DN-QDE-7HS-7SW-THS-8SW-8DN-JDE-JSS-KSW-9DN-ASE" },
			new String[] {
					"E",
					"A",
					"SWSSWESSNWNWWNWSEWESENNSESNSEENESNNNWSWNWEEWENNESEWW",
					"PAE-1NS-X1W-2HN-2SE-PAS-3CW-PAN-3NE-PAS-PAW-PAN",
					"3HS-QHW-2HN-4HE-ASW-2SN-4SE-JSS-3SW-8SN-QSE-4DS-5SE-8DS-KSW-9SN-6SW-2DN-TSE-2CS-7SE-8HS-3DW-TCN-7CE-4CS-JCW-QCN-JDN-5DE-QDS-6DW-KHS-AHW-6HN-5HE-ACW-TDN-7DE-5CS-KCW-9HN-9DE-8CS-6CW-JHN-KDE-9CS-ADS-3CW-THN-7HE" },
			new String[] {
					"S",
					"L",
					"SSSWWWSNWSEENSENWWNSEWSNWNEEEENWEWWSSSSNNENNWSNEEENW",
					"PAS-PAW-1SN-PAE-2NS-PAW-3SN-PAE-3NS-PAW-PAN-PAE",
					"5CW-9CN-QCE-2CS-2HE-AHS-7HW-6HN-KHS-9HW-2SN-3HE-QHS-THW-3SN-4HE-JHS-6DW-5SN-5HE-3CS-6CW-ACN-KCE-QDN-9DE-2DS-KDW-TCW-6SN-3DE-JCS-8CS-7CW-9SN-4SE-JDS-5DW-4DN-8HE-4CS-TDW-KSN-TSE-8DS-7SW-ADN-JSE-7DN-QSE-8SS-ASW" },
			new String[] {
					"W",
					"N",
					"WEWEWNESSEWWSWSNSSWSSWESWEEWEWWSNNWNSEENNENNNNSNNESE",
					"PAW-PAN-1CE-PAS-1HW-PAN-2NE-PAS-3CW-PAN-3SE-PAS-4DW-PAN-4HE-PAS-4SW-PAN-PAE-PAS",
					"ACS-2CW-7CN-3CE-3DS-2DW-4DN-JDE-ADE-5DS-7DW-7SN-8HN-AHE-7HS-3HW-ASE-9SS-4CW-2SN-5CE-9CS-QCW-3SN-JSN-QSE-KSS-6CW-TCS-KCW-5SN-8CE-9HN-2HE-QHS-5HW-6DS-TDW-6SN-JCE-TSN-4SE-8DS-6HW-JHN-KHE-9DS-THW-4HE-QDS-KDW-8SN" },
			new String[] {
					"N",
					"A",
					"ESENSWSEEWWWNNSNSSSSEWESNNEENEEWWWNENWSNWESNEWSWNWNS",
					"1NN-PAE-3CS-PAW-3DN-PAE-3NS-PAW-5DN-PAE-6DS-PAW-PAN-PAE",
					"TCE-3CS-JCW-ACN-4HN-2HE-AHS-8HW-3DS-TDW-ADN-9DE-THN-JHE-8DS-7HW-5DS-8SW-KDN-JDE-QHN-3HE-6DS-9HW-ASS-3SW-2SN-7SE-9SS-TSW-JSN-4SE-KSN-5HE-5SS-QSW-6SN-6HE-6CS-7CW-5CN-2CE-8CS-QCW-KCW-2DN-4CE-7DS-QDS-KHW-4DN-9CE" },
			new String[] {
					"E",
					"L",
					"ENSNESWESWSNSWWNEENWNWESEWNSSNSNWNEESSWWNEWNSEWNESWE",
					"PAE-1HS-PAW-PAN-X1E-2CS-2HW-PAN-2SE-X1S-PAW-4HN-PAE-PAS-PAW",
					"5SW-3SN-ASE-7SS-JHE-QHS-AHW-2HN-8HW-9HN-THE-KHS-4CS-8CW-KCN-2CE-3CN-6CE-QCS-JCW-ACS-2DW-5CN-9CE-TCS-3DW-6SN-6DE-7CS-2SW-TSN-4SE-QSS-KSW-5HN-8SE-4DN-5DE-QDS-ADW-9SW-7HN-JSE-6HS-9DN-KDE-4HS-TDW-3HS-8DW-7DN-JDE" },
			new String[] {
					"S",
					"N",
					"SESWESEWSSWENWWSWWNNEEWSSSWWNEENNSWNSNNNSEENNWNWEESE",
					"1CS-PAW-1HN-1SE-2DS-PAW-3HN-PAE-4HS-PAW-PAN-PAE",
					"TDE-ADS-2DW-7DN-9HS-THW-AHN-6HE-2SN-ASE-3SS-8SW-5SE-KSS-TSW-6SN-2CS-9CW-ACN-6CE-7SN-JSE-QHS-3DW-4CS-5CW-4HN-3CE-KHN-5HE-4DS-2HW-JHN-4SE-7CS-3HW-8DN-9DE-QDS-5DW-KDS-6DW-9SN-8CE-JCS-QCW-8HN-KCE-7HN-QSE-TCS-JDW" },
			new String[] {
					"W",
					"E",
					"WNESEEENSNEEENNSEESSWSWSWNNSWENWNSESNWWNWWSWNWNESWES",
					"1SW-PAN-2CE-PAS-2HW-PAN-5CE-PAS-PAW-PAN",
					"ASS-3SW-2SN-TSE-4DS-KDW-ADN-6DE-3DN-5DE-QDS-9DW-7DS-JDW-2DN-4CE-KCE-5CS-2CW-3CN-ACE-TCS-4HW-9CN-QCE-8DS-7HW-JCN-5HE-3HS-KHW-2HN-AHW-6HN-THE-9HS-QSW-9SN-KSE-JSS-8CE-TDS-8SW-QHN-7CE-JHS-6SW-8HN-6CE-5SS-4SW-7SN" },
			new String[] {
					"N",
					"L",
					"ENNSENWWWWWNSSNSSWESNSSWESESESWWEWESENENNSEEWNWNWNEN",
					"1SN-2HE-X1S-3HW-4SN-PAE-PAS-PAW",
					"2CE-ACS-QCW-3CN-4SS-9SW-TSN-KSE-6CE-5CS-8CW-KCN-ASN-6SE-3HS-7SW-QSN-5SE-5HS-JSW-9DN-KDE-2DS-6DW-7DE-ADS-QDW-3DN-JDS-9CW-4CN-2HE-TDS-TCW-7CN-4HE-8DS-6HW-KHN-8HE-5DS-JCW-8SN-AHE-3SN-QHE-4DS-9HW-2SN-THE-JHS-7HW" },
			new String[] {
					"E",
					"N",
					"SNSWSEEENNSESEENWWSESSWWWSNWSESWNWNEWSNNNNNESNEWEWWE",
					"PAE-1CS-1DW-1SN-2DE-2NS-PAW-3HN-PAE-4HS-PAW-PAN-PAE",
					"2DE-ADS-KDW-4DN-7DS-JDW-2HN-8DE-JCN-KCE-ACS-5CW-2CS-3HW-3CN-7CE-KSW-2SN-ASE-7SS-8CE-4CS-7HW-TCN-QHW-AHN-5HE-4HS-8HN-JHE-KHS-9HW-QCS-5DW-3SN-9CE-6CS-6DW-4SN-3DE-TDS-QDW-THN-6SE-8SN-JSE-6HS-QSW-9DS-TSW-5SN-9SE" },
			new String[] {
					"S",
					"E",
					"EEWWWWSSNWSNSSSWESNESNNSWNEEENSEWNNWWSWENNNNEWESSEWE",
					"1DS-PAW-1SN-PAE-1NS-X1W-2DN-2HE-2NS-PAW-3NN-PAE-PAS-PAW",
					"QHW-5HN-7HE-KHS-9DS-KDW-ADN-8DE-JDN-5DE-2DS-4DW-TDN-2HE-3DS-4CW-7DN-3CE-QDS-8HW-6DS-5CW-3SN-2CE-8CS-6CW-KCN-3HE-TCN-4HE-QCS-7CW-ACS-JCW-9HN-2SE-9CS-JHW-THN-7SE-JSS-8SW-4SN-QSE-ASE-TSS-KSW-5SN-9SE-6HS-AHW-6SN" },
			new String[] {
					"W",
					"A",
					"SNNESNSEWWESSSSNESNWESNESWWSNENEENEENSWWWNNWWWWEESWN",
					"1SW-PAN-1NE-X1S-2SW-3HN-PAE-4CS-PAW-PAN-PAE",
					"2SW-4SN-TSE-QSS-ACS-TCW-3CN-5CE-KCS-JCW-4CN-9CE-KHS-AHW-4HN-5HE-KSW-ASN-JSE-2DS-JDN-5DE-3DS-ADW-7SW-5SN-7HE-2CS-3HS-2HW-QHN-8HE-7DN-9DE-TDS-8DW-KDS-3SW-4DN-QDE-6DS-6SW-7CN-QCE-JHE-8CS-9SW-9HN-6CS-8SW-6HN-THE" },
			new String[] {
					"N",
					"L",
					"ENNSENWNESEESNEESEEESWSWWSWWSNNESNWWWWWNNEWSNSNNSEWS",
					"PAN-PAE-1NS-X1W-2SN-4NE-PAS-5DW-PAN-PAE-PAS",
					"TSN-4SE-6SS-KSW-THW-5HN-7HE-4HS-JHW-6HN-QSE-8HS-5SW-7SN-3DE-8SS-4DE-5DS-KDW-2DN-TDW-9HN-6DE-JDS-ADS-QDW-2SN-7DE-9DS-2HW-3SN-8DE-ASS-3HW-9SN-2CE-JSS-QHW-3CN-6CE-ACS-8CW-4CN-TCE-JCS-AHW-9CN-KCE-QCE-5CS-KHW-7CN" },
			new String[] {
					"E",
					"N",
					"NSNEEWSESSENEWSWNWWNSWSEWWESWNSEEWENWNSSNNWSNWNENESE",
					"1CE-X1S-1DW-4SN-PAE-PAS-5DW-PAN-6CE-PAS-PAW-PAN",
					"2SS-5SW-JSN-QSE-QDE-3DS-KDW-8DN-ADW-5DN-THE-9DS-8SW-9SN-ASE-6SS-TSE-KSS-7CW-3SN-2DW-5HN-6CE-JDS-2HE-3HS-QHW-KHN-4SN-5CE-8CS-4DW-AHS-4HW-JHN-8HE-6HS-9HW-2CN-7HE-7SN-9CE-TCS-6DW-3CS-7DW-KCN-ACE-QCE-JCS-TDW-4CN" },
			new String[] {
					"S",
					"E",
					"SNEWENEWNWNENNSSSESEWWENWSNNWNNSEEWEWSWNESNWESSEWWSS",
					"1SS-PAW-1NN-PAE-2DS-X1W-3CN-PAE-3SS-PAW-4SN-PAE-PAS-PAW",
					"TDW-QDN-6DE-3DS-2DN-8DE-ADS-9DW-4DS-KDW-2SN-JDE-5SN-TSE-KSS-6SW-ASS-JSW-2HN-3SE-9SS-QSW-3HN-7SE-AHW-5HN-8HE-7HS-4HW-6HN-JHE-KHS-8SS-5CW-3CN-4CE-7DS-9CW-7CN-6CE-5DS-JCW-TCN-9HE-2CS-THW-ACN-8CE-QCN-KCE-4SS-QHW" },
			new String[] {
					"W",
					"A",
					"SWSENSEWSWNNWSNSESENWSWSENWSWNENEWNSWSNWNEEWNSWNEEEE",
					"PAW-1CN-1SE-X1S-2SW-3HN-3SE-PAS-4SW-PAN-PAE-PAS",
					"JHS-QHW-AHN-6HE-3SN-KSE-8SS-2SW-5CE-2CS-JCW-QCN-7SN-QSE-2DS-6SW-ASE-4DS-9SW-TSN-8CE-4CS-ACW-6CN-3CW-KCN-5SE-7CS-5DE-QDS-9DW-3DN-TCS-9CW-5HN-8HE-KHS-2HW-7HN-JSE-7DE-6DS-JDW-ADN-8DN-KDE-TDS-9HW-4SE-3HS-4HW-THN" },
			new String[] {
					"N",
					"N",
					"WSEWESENEWWSSNSESWSEEWSSNWSWNSSWNNSNEENNEWWNNENWWEEN",
					"1SN-PAE-2DS-PAW-2HN-PAE-3HS-PAW-3SN-PAE-4HS-PAW-4NN-PAE-5DS-PAW-6HN-PAE-PAS-PAW",
					"6CE-ACS-5CW-9CN-2HS-7HW-8HN-QHE-8DE-3DS-TDW-KDN-AHN-KHE-5HS-3HW-ASN-8SE-3CS-5SW-2SN-3SE-6HS-4SW-KCS-2CW-2DN-4CE-QDS-ADW-9HN-4DE-6SN-QSE-THS-TSW-JDS-6DW-7SN-9DE-5DS-QCW-9SN-8CE-7CS-JCW-JHN-TCE-4HN-KSE-7DS-JSW" },
			new String[] {
					"E",
					"E",
					"ESNNNNEEWESSNWNWSWESEWNSSWSESSEWWNSWEENWNEEESNWWNNSW",
					"PAE-PAS-PAW-1CN-PAE-3NS-PAW-PAN-PAE",
					"4DW-3DN-9DE-KDS-KCS-TCW-4CN-2CE-QCS-2SW-5CN-8CE-3CS-9SW-ACN-9CE-3SN-4SE-KSS-ASW-2DW-JDN-7DE-5DS-6CN-JCE-2HS-7HW-KHE-4HS-8HW-AHN-7CN-3HE-7SS-6DW-QSN-5SE-5HS-TSW-JSN-6SE-THS-TDW-8SN-6HE-8DS-ADW-9HN-QHE-QDS-JHW" },
			new String[] {
					"S",
					"A",
					"SSSEWENWEWENSNENSWSSEESEWSEEWWWNWENNSNNWNWWENSWNSSEN",
					"1DS-PAW-1HN-PAE-2CS-PAW-3HN-PAE-4NS-PAW-5HN-PAE-6HS-PAW-PAN-PAE",
					"KSE-8SS-5SW-ASN-7HN-3HE-QHS-6HW-2CS-9CW-KCN-7CE-AHN-2HE-3CS-4HW-KHN-9HE-5DS-5HW-JHN-5CE-7DS-8HW-3SN-6SE-JSS-2SW-QSS-4SW-7SN-3DE-ACS-6CW-8CN-TCE-4CS-JCW-THN-QCE-TSN-9DE-8DS-9SW-2DN-TDE-ADS-6DW-JDS-KDW-4DN-QDE" },
			new String[] {
					"W",
					"L",
					"EEEEWWNWNNSSEENWSWNNWENWNNSSNSESWEWNWSWWESSNENEESSSW",
					"1DW-PAN-PAE-1SS-PAW-1NN-PAE-2HS-PAW-2SN-PAE-3HS-PAW-3NN-PAE-PAS-PAW",
					"TDE-5DS-QDW-ADN-8CN-ACE-QCS-6CW-2DE-2HS-9DW-JDN-KDN-5CE-3HS-6DW-7DN-2CE-5HS-4DW-8DN-3CE-4SS-8HW-3DN-4CE-5SS-7CW-6SN-7SE-JSS-ASW-9CW-JCN-6HE-KCS-KSS-2SW-8SN-3SE-QSS-THW-TCN-TSE-7HS-QHW-4HN-9HE-AHW-JHN-9SE-KHS" },
			new String[] {
					"N",
					"E",
					"EEWWESNSNSSSNWNNWENWNESSENESWSNNWEEEWSSWSWNEESEWWWNN",
					"1NN-PAE-2CS-PAW-2DN-PAE-3CS-PAW-4CN-PAE-4NS-PAW-5SN-PAE-5NS-PAW-6DN-PAE-6NS-PAW-PAN-PAE",
					"JHE-KHS-4HW-6HN-JDS-2DW-3DN-KDE-TDE-QDS-5DW-4DN-7CS-5CW-ACN-2CE-ADN-6DE-3HS-8DW-9DN-3CE-5HS-4CW-7DN-6CE-3SS-2SW-KSN-6SE-8SS-4SW-TCN-7SE-KCS-TSW-QCS-QHW-8CN-THE-JCS-8HW-7HN-9HE-9CS-QSW-ASN-2HE-AHS-JSW-5SN-9SE" },
			new String[] {
					"E",
					"A",
					"SENWSNSEEWWSSNWNSEEWWWSNSNWNNWSEWWNNWSSNESNEEEWENEES",
					"3SE-X1S-PAW-4HN-PAE-4NS-PAW-5DN-PAE-6NS-PAW-PAN-PAE",
					"9SW-2SN-TSE-ASS-KDS-8DW-2DN-7DE-JDS-3DW-4DN-6DE-ACS-5CW-4CN-3CE-KCS-JCW-7CN-9CE-2CS-QCW-5SN-TCE-2HW-THN-7HE-6HS-ADN-3SE-5DS-9DW-QDN-6SE-4SS-TDW-3HN-7SE-AHS-5HW-8CS-QHW-JHN-KSE-6CS-9HW-4HN-QSE-KHS-8HW-JSN-8SE" },
			new String[] {
					"S",
					"L",
					"SWNWWEWWWESSSWSWNEWSSESSNESSEENSWNWWEESWNNNEEENNENNN",
					"1DS-PAW-1SN-PAE-2HS-PAW-2SN-PAE-3CS-PAW-4NN-PAE-5HS-PAW-6SN-PAE-6NS-PAW-PAN-PAE",
					"QHE-2HS-8HW-6HN-7SE-2CS-2SW-9SN-ASN-6SE-3HS-6CW-KSN-8SE-7HS-2DW-QSN-JSE-3DS-4DW-TSN-7CE-8DS-7DW-5SN-JCE-9DS-THW-4SN-6DE-JDS-3CW-3SN-TDE-QDS-JHW-4CN-4HE-QCS-5CW-ACS-TCW-KDN-ADE-KCS-9CW-5DN-KHE-AHS-8CW-9HN-5HE" },
			new String[] {
					"W",
					"N",
					"SWWSWENEEWSNSSENEENESESSNEWEWSNWWSESSWNNNNNWENSNWEWW",
					"1HW-1SN-PAE-1NS-PAW-2SN-PAE-2NS-PAW-3NN-PAE-PAS-PAW",
					"4HW-6HN-THE-JHS-5HS-2HW-AHN-3HE-4DN-6DE-JDS-6SW-2DS-6CW-KDN-ADE-TCE-2CS-3CW-KCN-7DN-3DE-9DS-7HW-QDS-KSW-2SN-5DE-9HS-KHW-3SN-7CE-ASW-4SN-7SE-9SS-4CW-8CN-9CE-QCS-ACS-JCW-TSN-TDE-5CS-8HW-8SN-8DE-QHS-JSW-5SN-QSE" },
			new String[] {
					"N",
					"A",
					"SWWSSSSSWEEENWSWNNNESNEENSSWENNWWSNESWSWEWWNENEENWNE",
					"PAN-1SE-2CS-2SW-3DN-PAE-3HS-PAW-4HN-PAE-PAS-PAW",
					"4SW-JSN-ASE-2HS-2CS-3CW-ACN-KCE-KSN-7SE-5CS-QSW-6SN-TSE-9HS-5SW-7CS-TCW-5HN-JCE-5DN-JDE-ADS-4DW-8CS-4CW-THN-QCE-8SN-9SE-QHS-2SW-9DS-2DW-KDN-8DE-6HN-4HE-AHS-3HW-9CS-KHW-TDN-JHE-8HW-7DN-3SE-6CS-7HW-6DN-QDE-3DS" },
			new String[] {
					"E",
					"L",
					"NSESWSNSEWWNSNEESWWWNNESESWENNSWSEWNNSEWENSEENWEWWNS",
					"PAE-1NS-PAW-2CN-PAE-2DS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"QSW-4SN-7SE-ASS-3CS-JCW-KCN-4CE-4HN-3HE-KHS-2HW-8HS-7HW-JHN-AHE-4DE-QDS-6DW-2DN-ACS-QCW-2CN-TCE-9CS-6CW-8CN-3DE-7CS-7DW-8SN-9HE-5CS-8DW-9DN-JDE-ADS-THW-TDN-KDE-5SS-2SW-KSN-3SE-QHN-TSE-6HS-JSW-5HN-6SE-5DS-9SW" },
			new String[] {
					"S",
					"N",
					"SNSWESWNNSNSSWEWESWNNWWSNNEWWEEEEWESNEEESNSNSWSWEWNN",
					"1SS-PAW-2CN-4HE-5CS-PAW-6CN-PAE-PAS-PAW",
					"AHE-JHS-3HW-QHN-5DE-6DS-TDW-ADN-3CN-6CE-ACS-5CW-KCS-8CW-9CN-2HE-2CS-7DW-QCN-3DE-TCN-5HE-4CS-2DW-8DN-6HE-QDS-4DW-3SS-8SW-ASN-2SE-KDN-7HE-5SS-JDW-9DN-8HE-7SS-4HW-KSN-JSE-9SS-TSW-6SN-KHE-JCS-QSW-7CS-9HW-4SN-THE" },
			new String[] {
					"W",
					"E",
					"SEWSSNESEENWNWWWNNSWNSNSNSNWSWWEWEWENSWSEEEENENSEWNS",
					"PAW-1NN-PAE-3NS-PAW-PAN-PAE",
					"5SE-2SS-QSW-KSN-5DN-3SE-QDS-4DW-ADS-2DW-6DN-4SE-2CS-KCW-ACN-8CE-9DN-6SE-TDS-3DW-7DS-8DW-KDN-3CE-2HN-7HE-KHS-AHW-3HW-QHN-9HE-4HS-JDN-8SE-5CS-4CW-7SN-JSE-ASS-5HW-TSS-6HW-9SN-TCE-6CS-8HW-QCN-JCE-7CN-JHE-9CS-THW" },
			new String[] {
					"N",
					"L",
					"SNWWESWESSEWSWEWENNEWWSSNSWSNENWESENNWSWNENNESNEWSNE",
					"PAN-PAE-1CS-PAW-1SN-PAE-2NS-PAW-3HN-PAE-3NS-PAW-PAN-PAE",
					"2DW-6DN-8DE-ADS-AHS-2HW-4HN-THE-9HS-KHW-6HN-8HE-5CW-3CN-QCE-2CS-3DE-QDS-4DW-7DN-ACS-4CW-3SN-6CE-JCS-KCW-5SN-9CE-8CW-6SN-5DE-TCS-3HS-7HW-JHN-5HE-QHN-4SE-8SS-9DW-KDN-7SE-JDS-TDW-9SN-TSE-QSS-2SW-7CS-JSW-KSN-ASE" },
			new String[] {
					"E",
					"N",
					"ESWEESSNWWWWSNEESWEWEESEWWNESNNEWSNNNSNNNSNNSSEWWEWS",
					"PAE-PAS-1CW-3HN-PAE-4HS-PAW-PAN-PAE",
					"2CE-ACS-KCW-9CN-4HS-8HW-JHN-7HE-2HN-3HE-KHS-8DW-9HS-6DW-AHN-5CE-QHN-6CE-4SS-4CW-THN-7DE-5DS-TSW-2SN-9SE-ASS-JSW-7SS-KSW-3SN-QSE-QCW-5HN-3DE-3CS-5SN-4DE-8SS-JCW-7CS-TCW-6HN-9DE-6SN-TDE-JDS-KDW-2DN-QDE-8CS-ADW" },
			new String[] {
					"S",
					"E",
					"WEWWWSSSSNWNSSNNENEWEESNWWWNEWNSSSENSWNEESNENEEWWENS",
					"1CS-PAW-1HN-PAE-2HS-PAW-3NN-PAE-4HS-PAW-PAN-PAE",
					"3CE-7CS-2CW-JCN-5SN-6SE-ASS-TSW-QHS-KHW-AHN-4HE-JHN-THE-7HS-2HW-KSN-2SE-4SS-JSW-KCN-7DE-8CS-4CW-3HN-3SE-9HS-5HW-ACS-5CW-3DN-8SE-9CS-6CW-4DN-9SE-TCS-QCW-6DN-5DE-ADW-QDN-9DE-2DS-8DW-6HN-TDE-JDS-7SN-QSE-8HS-KDW" },
			new String[] {
					"W",
					"A",
					"SNSENSESNSWNNENWSSEWNSSSESESWWNWWWWWNEWEEENENNWWEENS",
					"4HW-PAN-PAE-7DS-PAW-PAN-PAE",
					"QCW-ACN-8CE-2CS-9DN-7DE-5DS-8DW-3DN-2DE-TDS-4DW-ADS-7HW-6HN-KDE-ASS-9SW-5SN-6SE-4CS-4HW-KCN-5CE-KSN-2SE-3HS-TSW-3CN-3SE-JCS-5HW-QDS-8HW-7SN-4SE-7CS-9HW-TCN-JSE-QHN-KHE-JDS-AHW-6DS-JHW-8SN-2HE-9CS-THW-6CN-QSE" },
			new String[] {
					"N",
					"L",
					"NENNSWSNNNSSSSWNSESSEWENWSNWENSNWEENEWEWWEEWENEWSSWW",
					"PAN-PAE-2NS-PAW-3SN-PAE-4CS-PAW-PAN-PAE",
					"ASW-8SN-7SE-JSS-7CW-2CN-3CE-ACS-QSS-KSW-4CN-4SE-2HN-AHE-6HS-3HW-6DE-2DS-KDW-4DN-KHW-5HN-4HE-6CS-KCS-6SW-5CN-9DE-ADS-3DW-QDN-JDE-8DS-TDW-9CN-9HE-7HN-THE-8CS-8HW-5DS-2SW-TCN-5SE-JCN-QHE-QCS-TSW-7DS-3SW-JHN-9SE" },
			new String[] {
					"E",
					"N",
					"NESNSESWWSWNENWSEESWEEWNSNNNSNWEWWNSESWESEEWSWWNNNSE",
					"PAE-PAS-PAW-1CN-PAE-3NS-PAW-PAN-PAE",
					"6HW-2HN-QHE-KHS-3SS-6SW-TSN-ASE-7HE-4HS-AHW-3HN-QCW-KCN-ACE-4CS-7CE-JCS-9CW-2CN-JHS-8HW-5HN-3CE-4DS-8DW-ADN-6DE-QDN-5DE-7DS-3DW-2DN-9DE-KDS-JDW-KSS-8SW-JSN-2SE-7SS-9SW-QSN-4SE-THN-TDE-6CS-9HW-5CN-5SE-8CS-TCW" },
			new String[] {
					"S",
					"E",
					"WESSSWNENNNSNNSEEWNESNWSNWESWEWNWEEWWSWNWNSSEEESENWS",
					"1CS-1HW-2HN-PAE-2SS-PAW-4CN-PAE-4HS-PAW-4SN-PAE-PAS-PAW",
					"2CW-8CN-9CE-KCS-3DS-ADW-2DN-4DE-6DW-7DN-8DE-9DS-5SS-KSW-2SN-8SE-3SW-4SN-JSE-ASS-6SS-7CW-QSN-7SE-TDN-5DE-QDS-JDW-TSS-4HW-7HN-9SE-4CS-6HW-ACN-3CE-QCN-THE-6CS-AHW-JCN-9HE-5CS-QHW-TCN-5HE-KHS-JHW-KDN-2HE-3HS-8HW" },
			new String[] {
					"W",
					"A",
					"NWEWESENESWSSEWWNWWNSSSSSNWNSESWEESSWNNWENNENWWEEENN",
					"PAW-1SN-PAE-2DS-PAW-3NN-PAE-4CS-PAW-4DN-PAE-4NS-PAW-5SN-PAE-5NS-PAW-6HN-PAE-7NS-PAW-PAN-PAE",
					"5HE-THS-QHW-AHN-ADN-2DE-9DS-7DW-5DN-6CE-TDS-3DW-JDS-4DW-8DN-4CE-QDS-6DW-4SN-8CE-KDS-2SW-5SN-TCE-4HS-7HW-KHN-8HE-ASN-3SE-7CS-8SW-KSN-6SE-JCS-9SW-2CN-TSE-KCS-3CW-ACS-5CW-9CN-JSE-JHS-2HW-3HN-9HE-6HS-QCW-7SN-QSE" },
			new String[] {
					"N",
					"N",
					"WNESWENSESSENSENEWNNWEEWSWEENSWESSNNWWWWWWSNNNEESSSN",
					"PAN-PAE-1NS-PAW-PAN-PAE",
					"AHW-4HN-2HE-5HS-KHW-THN-3HE-8HS-QHW-JHN-7HE-9HS-6HW-4DN-7CE-5SS-ADW-7DN-5DE-2DS-2SW-6SN-9SE-KSS-QSS-3SW-7SN-TSE-JSS-4SW-8SN-4CE-KDS-6DW-8DN-3DE-QCS-2CW-3CN-KCE-TCE-JCS-6CW-8CN-9CS-QDW-ACN-JDE-ASN-TDE-5CS-9DW" },
			new String[] {
					"E",
					"E",
					"ESEWSNESSSWSSNEWESWWWSEEENSEWNWNWNWNSWNSNENENENWWSNE",
					"PAE-3NS-PAW-PAN-PAE",
					"6HW-5HN-3HE-QHS-2HS-4HW-7HN-2CE-3SN-6SE-QSS-TSW-2SS-JSW-KSN-ASE-KDE-6DS-7DW-ADN-AHN-5DE-TDS-8HW-9SN-4SE-3CS-THW-7CN-4CE-ACS-5CW-KCS-QCW-2DN-8CE-JCS-9DW-JHN-QDE-TCS-8DW-9HN-JDE-9CS-4DW-7SN-3DE-6CS-KHW-5SN-8SE" },
			new String[] {
					"S",
					"A",
					"SNWNNNEWENSSENNWWSWSSSEEWSEEWWEEWSNEEWNSSWNNSWEWNSEN",
					"PAS-PAW-PAN-1HE-X1S-2HW-2SN-3HE-3SS-4HW-PAN-PAE-4SS-PAW-PAN-PAE",
					"QDE-ADS-7DW-2DN-2SS-8SW-JSN-KSE-QHE-9HS-5HW-AHN-ASN-9SE-3SS-4SW-5SN-8CE-QSS-TSW-KCS-9CW-3CN-ACE-6HE-7SS-4HW-THN-QCS-4CW-5CN-TCE-2CS-4DW-JCN-2HE-7CN-3HE-6DS-8HW-6CN-JDE-8DS-5DW-6SN-7HE-9DS-KDW-3DN-JHE-TDS-KHW" },
			new String[] {
					"W",
					"L",
					"NNEEWWSWNSNSSSNWWWSNEWWENSESWENEEENEWNWESSSSNWSENEWN",
					"PAW-1CN-PAE-1SS-PAW-1NN-PAE-2CS-PAW-2HN-PAE-2NS-PAW-4SN-PAE-PAS-PAW",
					"JDW-3DN-9DE-ADS-3HS-4HW-KHN-7HE-ASN-2SE-3SS-8SW-7SN-TSE-4SS-KSW-AHW-6HN-2HE-5SS-8CS-9CW-QCN-5CE-THN-5HE-6SS-QHW-ACS-6CW-2CN-4CE-KCS-7CW-3CN-QSE-JHE-2DS-4DW-JSN-KDN-QDE-7DS-5DW-TCN-9HE-JCS-TDW-9SS-6DW-8DN-8HE" },
			new String[] {
					"N",
					"E",
					"WNESNEESSESENENNWSSWWSNWWSWWWSWNEENEENNSNWWEENNEWSSS",
					"1CN-PAE-1SS-PAW-1NN-PAE-3NS-PAW-PAN-PAE",
					"QHE-5HS-6HW-7HN-8HE-6DS-2HW-THN-3CN-KCE-5CS-2CW-JHE-7DS-3HW-KHN-6CN-7CE-9CS-5DW-TCS-8DW-ACN-4CE-AHN-9HE-TDS-4HW-3SN-6SE-QSS-4SW-KSS-5SW-8SN-7SE-QCS-9DW-3DN-8CE-ASS-JSW-9SN-TSE-ADS-KDW-JDN-2DE-2SS-QDW-4DN-JCE" },
			new String[] {
					"E",
					"A",
					"NSWWNNSSWEEWNSWWNWNSNSNEWSSENWSEEENWENNSEEENEWWESSSW",
					"PAE-PAS-PAW-1DN-PAE-1NS-PAW-2CN-PAE-2NS-PAW-3CN-PAE-3NS-PAW-PAN-PAE",
					"8SW-6SN-TSE-JSS-2HS-5HW-AHN-3HE-JDN-QDE-ADS-6DW-TDS-KDW-5DN-7HE-ASW-2CN-7SE-2SS-9SW-6CN-3SE-QSS-KSS-5CW-4HN-4SE-8DS-3DW-7DN-5SE-2DS-4DW-9DN-8HE-ACN-JCE-3CS-4CW-KHN-9HE-6HS-JHW-THN-QHE-8CS-TCW-QCE-9CS-KCW-7CN" },
			new String[] {
					"S",
					"L",
					"WNNWNENSSNESSWSEWSSSNNNESWWEESEWWNSEEEENNWSNNWESWWEW",
					"PAS-PAW-PAN-1HE-PAS-3HW-PAN-3SE-4DS-4NW-PAN-5DE-PAS-6HW-PAN-PAE-PAS",
					"ACS-2CW-3CN-7CE-KCS-5CW-4CN-QCE-5SS-4SW-7SN-9SE-JHE-5HS-2HW-9HN-QHE-THS-7HW-2SN-4DE-6DS-ADW-9DN-8SW-3SN-KSE-TSS-3HE-3DS-8HW-6CN-ASW-6SN-QDE-9CS-QSW-JCN-AHE-TCS-KHE-KDS-JSW-8CN-6HE-8DS-5DW-JDN-4HE-7DS-2DW-TDN" },
			new String[] {
					"W",
					"N",
					"NWNSEEWSSWWNNSEEWEWNNNESEESNSWWENWWNSWSEENSESSESWWNN",
					"PAW-1CN-1DE-1SS-2HW-X1N-3DE-PAS-PAW-PAN",
					"5CS-JCW-KCN-7CE-ASN-2SE-5SS-JSW-8DN-ADE-2DS-5DW-7HE-AHS-5HW-3HN-TCS-QCW-ACN-6CE-KSN-3SE-7SS-QSW-TDN-JDE-QDS-7DW-9CS-3CW-2CN-4DE-KDE-8SS-8CW-9DN-9SE-TSS-6HW-4SN-QHS-KHW-JHN-6DE-3DE-4HS-THW-8HN-6SE-2HS-9HW-4CN" },
			new String[] {
					"N",
					"A",
					"SNNWWSWWWWEESSNWWNSEEWWENSNNNSSEESEESSNWEWENSSNEENWN",
					"1DN-PAE-3NS-PAW-PAN-PAE",
					"JCW-3CN-QCE-ACS-5HS-5CW-AHN-8HE-4HN-THE-KHS-5DW-2DS-TDW-KDN-8DE-2HN-7HE-9HS-6CW-QHS-8CW-3HN-JHE-6HS-4DW-4CN-9DE-8SS-2SW-QSN-3SE-ASN-5SE-7SS-4SW-6DN-QDE-ADS-JDW-7DS-9CW-3DN-TSE-2CS-TCW-6SN-KCE-JSE-7CS-KSW-9SN" },
			new String[] {
					"E",
					"L",
					"SESWWEWNNNSWESNSSWESENNESNWENEWWEEWSSSSNENEEWWWSNNNW",
					"PAE-1DS-PAW-1SN-PAE-2DS-PAW-3DN-PAE-3NS-PAW-4SN-PAE-4NS-PAW-5DN-PAE-5NS-PAW-6DN-PAE-6NS-PAW-PAN-PAE",
					"6HW-4HN-8HE-JHS-TSS-ASW-2SN-3SE-2HW-9CN-9HE-QHS-2DS-6DW-ADN-7DE-KSN-5SE-2CS-8SW-QSN-6SE-4CS-7SW-JSN-9DE-QCS-9SW-4SN-3CE-4DS-5CW-JDN-QDE-KDS-6CW-AHS-7HW-TCN-3HE-8DS-THW-3DN-7CE-KHS-8CW-JCN-5HE-5DS-KCW-TDN-ACE" },
			new String[] {
					"S",
					"N",
					"NNNSSENSNSWEWSNSSWWNWNENSWSWNWSSWEENNEESEWWWSEEEEWNE",
					"1SS-PAW-1NN-X1E-PAS-PAW-2CN-PAE-PAS-PAW",
					"AHE-2HS-3HW-4HN-JDE-2DS-7DW-3DN-ASE-2SS-6SW-KSN-JSE-7SS-4SW-2CN-3CN-KCE-5CS-ACW-ADW-8DN-3SE-4DS-6DW-TDN-7CE-5DS-KHE-6HS-5HW-JHN-THE-7HS-8HW-QHN-4CN-8SE-JCS-QCW-9DW-QDN-9HE-KDS-9CS-QSW-TCN-TSE-8CN-9SE-6CS-5SW" },
			new String[] {
					"W",
					"E",
					"WSWNNSSEEWNSENSSENSSWEWSESWNENSWWSENENEWEWNNNNWEWESW",
					"PAW-PAN-1NE-2DS-2SW-PAN-PAE-2NS-X1W-3DN-PAE-PAS-PAW",
					"2HW-5HN-THE-6HS-3SE-KSS-ASW-5SN-7HW-KHN-AHE-9HS-QSE-7DS-4SW-6SN-8DS-9DW-2DN-5DE-JDW-6DN-KDE-ADS-QDS-8HW-5CN-TDE-3CS-4CW-QCN-ACE-TSE-4DS-2SW-7SN-KCS-2CW-6CN-9CE-7CS-JCW-3HN-TCE-JSW-8SN-QHE-3DS-8CS-9SW-JHN-4HE" },
			new String[] {
					"N",
					"L",
					"NSWWSNESNEEESEWEENWEWWSSSSEEESWEWEWWNNNSSSNWNNNNWSWN",
					"1SN-PAE-2DS-PAW-2SN-PAE-4NS-PAW-5HN-PAE-6NS-PAW-PAN-PAE",
					"TDW-6DN-5DE-ADS-5HS-8HW-QHN-2HE-TSN-2DE-2SS-JSW-5CW-2CN-JCE-ACS-KDS-3DW-7CN-4DE-QDS-7DW-TCN-8DE-JDS-9DW-5SN-8CE-QSS-6SW-7SN-QCE-4SS-KSW-ASN-3HE-AHN-9HE-9CS-JHW-KHN-7HE-6CS-THW-9SN-KCE-3SS-4CW-8SN-4HE-3CS-6HW" },
			new String[] {
					"E",
					"N",
					"NWESNESWWWWSSEWNENSWSENNWNNSEESNSNNWWEWESSEEEEWWSSNN",
					"PAE-PAS-1CW-1DN-PAE-1NS-PAW-2HN-PAE-2NS-PAW-3NN-PAE-PAS-PAW",
					"QCW-2CN-7CE-ACS-3SS-9SW-KSN-2SE-ASN-5SE-4SS-TSW-6CN-4CE-KCS-9CW-JSS-3DW-2HN-6SE-QSS-3CW-7HN-7SE-7DS-8DW-JDN-2DE-ADN-5DE-9DS-KDW-QDN-TDE-5CS-TCW-6DN-4HE-8CS-JHW-4DN-8SE-3HS-QHW-THN-KHE-8HS-AHW-JCW-9HN-5HE-6HS" },
			new String[] {
					"S",
					"E",
					"SNSSEEEEWWWSNSWNESSWWNWSENSEESNEWWEWNNNSNWEWNNENESSW",
					"PAS-PAW-1CN-PAE-1NS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"3DW-4DN-KDE-2DS-5SE-2SS-ASW-3SN-QCW-ACN-7CE-2CS-7SN-9SE-QSS-6SW-6DS-8DW-TDN-5DE-ADN-6CE-7DS-9DW-AHN-7HE-2HS-8HW-3CN-8CE-KCS-TCW-QDS-JDW-6HN-9CE-KSS-4SW-8SN-JSE-5HS-9HW-QHN-3HE-KHN-THE-5CS-JHW-TSN-4HE-4CS-JCW" },
			new String[] {
					"W",
					"A",
					"WEWESEWNSNSNNWENWSWWEESSNSEESSNWNSSWWWENENWNEENWSENS",
					"PAW-1SN-PAE-2HS-PAW-2SN-PAE-4NS-PAW-5DN-PAE-6SS-PAW-PAN-PAE",
					"TDE-6DS-7DW-KDN-2SN-3SE-JSS-5SW-ASS-TSW-4SN-7SE-6CS-8CW-KCN-3CE-KSN-8SE-4HS-2CW-4DN-3DE-JDS-2DW-QDS-5DW-6HN-9DE-ADS-8DW-8HN-QSE-5CE-QCS-4CW-9CN-TCS-KHW-ACN-7CE-9SN-AHE-THS-QHW-6SN-3HE-9HS-JHW-JCN-2HE-5HS-7HW" },
			new String[] {
					"N",
					"L",
					"SSSEWWWWSWEENEENNNEWNSNSSNEENWWSENSWNSWNWWESNWESNESE",
					"1DN-PAE-2NS-PAW-3DN-PAE-4DS-PAW-5DN-PAE-PAS-PAW",
					"KCE-2CS-6CW-ACN-4DN-2DE-KDS-8DW-QDS-3SW-5DN-3DE-TDS-4SW-6DN-7DE-7HS-6HW-9HN-2HE-4HN-3HE-KHS-AHW-7CW-9DN-5CE-3CS-QHN-8HE-THS-5HW-2SN-5SE-TSS-8SW-4CS-8CW-JDN-QCE-7SN-ASE-6SS-9CW-9SE-KSS-JCW-JSN-TCS-JHW-ADN-QSE" },
			new String[] {
					"E",
					"N",
					"EWESSSEESWENEWNWWSNNSENWSWEWWWENNNEENSSWSNEWNNSWENSS",
					"PAE-1NS-PAW-2CN-3CE-3NS-PAW-PAN-PAE",
					"JCW-KCN-ACE-5CS-2CE-6CS-3CW-3DN-AHS-3HW-7HN-6HE-KHS-4HW-8HN-2HE-ASS-2SW-4SN-5SE-KSS-6SW-8SN-JSE-9SS-TSW-QSN-4CE-7DN-TDE-KDS-ADW-QDW-8DN-THE-6DS-2DW-JDN-8CE-9DS-QHN-JHE-7CS-5HW-9HN-QCE-TCS-5DW-7SN-9CE-3SS-4DW" },
			new String[] {
					"S",
					"E",
					"NEWNESESNWEESNNWSESEWNWNSSSNWEEENWENSSESWSSWNEWWNWWN",
					"1NS-2SW-3NN-PAE-PAS-PAW",
					"KSW-ASN-8SE-2SS-3HN-5HE-QHS-9HW-KDS-9DW-2DN-8DE-2HS-4HW-JHN-AHE-KCE-ACS-JCW-2CN-5SS-QSW-7SN-6CE-4CW-5CN-QCE-7CS-6HE-KHS-4DW-8HN-5DS-JDW-QDN-6DE-3DN-3CE-ADS-3SW-9CS-TSW-TCN-8CE-TDN-THE-7DS-9SW-JSN-7HE-4SS-6SW" },
			new String[] {
					"W",
					"A",
					"NNWNWNWEWEEESEENWENSWEEESWSSSWSNNWWSESESSWWNENWNSNNS",
					"PAW-PAN-1DE-1HS-PAW-1SN-2DE-3DS-PAW-3NN-PAE-4SS-PAW-PAN-PAE",
					"KCE-ACS-6CW-2CN-2SS-4SW-KSN-7SE-8HN-AHE-2HS-5HW-QCE-ASS-4CW-3CN-3SS-5SW-QSN-6DE-6SN-2DE-JSS-9SW-KHS-9HW-7HN-QHE-JHS-THW-5CN-9CE-6HS-5DW-7CN-3DE-4HS-9DW-4DN-TDE-3HS-8CW-7DN-JDE-KDS-ADW-TSN-QDE-8SN-JCE-8DS-TCW" },
			new String[] {
					"N",
					"N",
					"WWNSWWEWWNEEEESSWESNEWNNSNEENNWSSNWSSWSNEEWNEWSENSSN",
					"1DN-PAE-1HS-PAW-1SN-PAE-2DS-PAW-2HN-PAE-3CS-PAW-3HN-PAE-4NS-PAW-5HN-PAE-6HS-PAW-PAN-PAE",
					"5SW-ASN-7SE-9SS-4HN-3HE-JHS-KHW-8SW-2SN-3SE-KSS-AHS-6HW-5HN-2HE-QHS-THW-9HN-8CE-QSS-7CW-6SN-4SE-KDS-5DW-8DN-2DE-3DS-TDW-JDN-6DE-QDN-9DE-4DS-2CW-ADN-QCE-7DS-3CW-JSN-TSE-5CS-6CW-JCN-ACE-8HS-TCW-7HS-9CW-4CN-KCE" },
			new String[] {
					"E",
					"E",
					"SNEENSSESWEWEWNSSSSSNWNSSSEWEENNENWNEEWNWENWWWWWENSN",
					"1HE-1NS-2HW-PAN-3HE-4NS-PAW-5DN-PAE-PAS-PAW",
					"KHE-4DS-3HW-7HN-KSS-7SW-2SN-4SE-KDS-2DW-3DN-4CE-5DS-TDW-JDN-JSE-9DN-2HE-6DS-3SW-ASN-5CE-TCS-6SW-QSN-9CE-8CS-8SW-3CN-QCE-2CS-JCW-ACE-7CS-KCW-6CN-QHE-ADS-AHW-JHN-QDS-THW-9HN-8HE-8DS-TSW-6HN-5HE-7DS-9SW-5SN-4HE" },
			new String[] {
					"S",
					"A",
					"WNENSNEEESESNSWWSENNNENSSNNWWWEWSSSEEWESWWNWWEESSNWN",
					"1NS-PAW-3CN-PAE-3DS-PAW-3NN-PAE-4NS-PAW-5SN-PAE-6DS-PAW-PAN-PAE",
					"2CW-3CN-QCE-KCS-KDS-3DW-7DN-6DE-2DS-4DW-JDN-TDE-5CN-8CE-JCS-3HW-6CS-4HW-ACN-4CE-7CN-9CE-5DS-5HW-TSS-3SW-5SN-9SE-2SS-4SW-QSN-8SE-ASN-6HE-JSS-6SW-2HN-AHE-8HS-7HW-QHE-THS-KHW-ADN-9DN-JHE-QDS-KSW-9HS-7SW-8DN-TCE" },
			new String[] {
					"W",
					"L",
					"ENESWSNESSEEWWWWENWSNSNSNESESWNSNNWWNWSNSEESNEWWENEW",
					"1DW-PAN-1SE-1NS-PAW-2CN-X1E-PAS-2SW-PAN-3SE-PAS-4SW-PAN-5CE-PAS-PAW-PAN",
					"AHS-5HW-8HN-3HE-8DS-2DW-KDN-ADE-2CE-5CS-ACW-8CN-KHW-6HN-5DE-2HS-6CW-3CN-9CE-JCS-QDS-3DW-6DN-4CE-QCE-7CS-4DW-9HN-KCE-TCS-7DW-2SN-4SE-3SS-9SW-QSN-9DN-5SE-TDS-TSW-7HS-THW-QHN-8SE-JDN-KSE-4HS-JHW-7SN-JSE-6SS-ASW" },
			new String[] {
					"N",
					"E",
					"SSWENNESESSWWSWWNEESWWENSWWNENENNNESSESEWNEWENNSNWSW",
					"PAN-PAE-PAS-1DW-PAN-PAE-1NS-2SW-PAN-3HE-PAS-3NW-PAN-PAE-PAS",
					"8HN-THE-JHS-2HW-2CS-ACW-7CN-5CE-3DW-QDN-6DE-2DS-3HN-KHE-AHS-3SW-JCS-KCW-6CN-8CE-ADW-5DN-7DE-8DS-4DW-5HN-JDE-KDS-QCS-4CW-7HN-TCE-9CS-6SW-9HN-4HE-3CS-QSW-4SN-6HE-QHS-TDW-8SN-2SE-KSS-ASW-JSN-7SE-9DW-9SN-5SE-TSS" },
			new String[] {
					"E",
					"A",
					"NNWWEESWSWSESENNWNWNESSWSSNENSWSEWENNSWEENWEWSWNEENS",
					"PAE-2NS-PAW-3CN-PAE-3DS-PAW-3NN-PAE-PAS-PAW",
					"4CW-2CN-KCE-ACS-KHS-AHW-2HN-3HE-5CW-3CN-7CE-8CS-7HS-6HW-QHN-8HE-3DN-9DE-TDS-QDW-9CW-4SN-6CE-TCS-ADS-7DW-4DN-2DE-KDS-5DW-6DN-THE-JDS-JCW-8DN-2SE-QCS-9HW-4HN-3SE-ASS-5SW-TSN-6SE-5HS-9SW-JHN-QSE-KSN-JSE-8SS-7SW" },
			new String[] {
					"S",
					"L",
					"ENENNEWSESWSSWNWENWESWNENNWSSWENWSWENSNNSEESWSWESWEN",
					"1CS-PAW-1DN-PAE-1HS-PAW-3NN-PAE-PAS-PAW",
					"4SE-JSS-QSW-2SN-7SW-ASN-5SE-3SS-7HN-6HE-KHS-5HW-3HS-2HW-QHN-JHE-AHN-7CE-4HS-8HW-3CN-2CE-ACS-8CW-KCS-QCW-5CN-4CE-JCS-2DW-6CN-TCE-9CS-4DW-3DN-5DE-9DS-7DW-ADN-8DE-KDN-QDE-6SS-TDW-JDN-KSE-9HS-THW-6DN-TSE-8SS-9SW" },
			new String[] {
					"W",
					"N",
					"WSNEESSWNWSENEEWEWNWNWWSWENESENNSNNWESWSSSSENSWENNWE",
					"1DW-PAN-3NE-PAS-PAW-PAN",
					"3CS-9CW-ACN-5CE-4CN-KCE-7CS-2CW-3DE-QDS-KDW-9DN-4DW-7DN-ADE-2SS-6SE-3SS-KSW-7SN-6DW-2HN-2DE-4SS-JDW-6HN-5DE-4HS-TDW-TCN-TSE-5SS-8DW-7HN-6CE-8SS-AHW-9HN-5HE-8HS-JHW-THN-3HE-KHS-QCS-JCW-QSN-QHE-8CS-9SW-JSN-ASE" },
			new String[] {
					"N",
					"A",
					"WWESENNNSNEWSNEWSSEWWNWENNSWESNWESNESEWNESWSENWSNSEW",
					"PAN-PAE-PAS-1NW-PAN-2CE-PAS-2DW-PAN-3NE-PAS-PAW-PAN",
					"7CN-4CE-TCS-KCW-4DW-KDN-3DE-5DS-8CN-QCE-ACS-3CW-5CS-2CW-9CN-6CE-JCN-3SE-6DS-3HW-ADN-7DE-4SS-8DW-2DN-QDE-2HS-9DW-4HE-5HS-AHW-6HN-JDW-TDN-8HE-6SS-7HW-THN-JHE-QHS-TSS-5SW-2SN-KSE-KHE-9HS-9SW-8SN-7SE-QSS-ASW-JSN" },
			new String[] {
					"E",
					"L",
					"NWWWEEESESNSWNNSESEWSSSNNSEWESESEWSWNNSWWNWEWNNWNEEN",
					"PAE-1NS-PAW-2HN-PAE-2SS-PAW-3DN-PAE-6DS-PAW-6NN-PAE-7DS-PAW-PAN-PAE",
					"4HE-5HS-9HW-KHN-2DN-7DE-JDS-8DW-7HS-3HW-QHN-2HE-3DN-5DE-ADS-5CW-AHS-JHW-2CN-6HE-THS-2SW-QCN-8HE-9CS-ACW-QDN-6CE-KDN-KSE-TDS-TSW-ASN-QSE-9DS-7SW-6DS-5SW-JSN-6SE-4DS-3SW-9SN-TCE-KCS-4CW-8SN-8CE-JCS-3CW-4SN-7CE" },
			new String[] {
					"S",
					"N",
					"SNWESSNSNSWSWWENWWSWNESWNSEWSSNWWEEENNNSNEENEWNEEEWS",
					"1CS-PAW-1HN-PAE-1NS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"5DW-4DN-TDE-JDS-4HS-3HW-AHN-2HE-3CN-5CE-9CS-QCW-2DW-KDN-3DE-7DS-8CN-7SE-2CS-ACW-6DW-9DN-4SE-ADS-6CS-4CW-TCN-5SE-3SN-TSE-ASS-8SW-KCS-8DW-6SN-9HE-JCS-7HW-9SN-THE-7CS-8HW-6HN-JHE-5HS-QDW-QHN-JSE-KHN-QSE-2SS-KSW" },
			new String[] {
					"W",
					"E",
					"NNEWSSSSNNNEEEWESWSNWSNESEENNWNNWWSESNSEEWWSWWWESNEW",
					"PAW-PAN-1DE-X1S-PAW-3HN-PAE-PAS-PAW",
					"ACE-6CS-5CW-2CN-JHE-QHS-5HW-3HN-THS-8HW-4HN-2HE-AHS-9HW-6HN-4DE-7CS-3DW-TCN-KCE-3SE-JSS-ASW-QSN-6DW-JDN-ADE-5DS-KSE-6SS-4SW-7HN-QCN-4CE-8CS-9DW-JCN-2SE-9CS-5SW-3CN-2DE-7DS-7SW-8DN-QDE-KDS-8SW-TDS-9SW-KHN-TSE" },
			new String[] {
					"N",
					"L",
					"SSSNESEWEESEEENENSWESNWWESWSWNSNWWNNWSWNNNWNNWWSESEE",
					"PAN-1CE-2CS-2HW-PAN-3DE-PAS-3HW-PAN-3NE-PAS-4DW-PAN-4SE-PAS-5DW-PAN-6DE-PAS-PAW-PAN",
					"2CS-9CW-5CN-JCE-2DE-9DS-JDW-3DN-5SW-2SN-ASE-TSS-KCE-3CS-2HW-5DN-3SN-JSE-QSS-8SW-3HS-QHW-7HN-6CE-AHW-5HN-TCE-6HS-7DW-TDN-KDE-ADS-6DS-QDW-4SN-4DE-4HW-JHN-8CE-KHS-QCS-9HW-THN-ACE-8DE-7CS-8HW-7SN-KSE-4CS-9SW-6SN" },
			new String[] {
					"E",
					"N",
					"SEEWSSEEWESWNWESWWWEWSSNSSNESNESNWNENNEWWNNENENSWNSW",
					"PAE-1DS-PAW-1HN-PAE-1NS-PAW-4HN-PAE-PAS-PAW",
					"8SE-TSS-JSW-QSN-QDN-8DE-ADS-2DW-KDS-5DW-4SN-3DE-4HS-9HW-QHN-AHE-3CE-2CS-TCW-ACN-5SN-6SE-KSS-ASW-6DW-THN-JHE-4DS-JCE-QCS-KCW-2HN-KHN-6HE-7HS-3SW-8HN-3HE-7CS-2SW-5HN-9CE-6CS-5CW-9SN-8CE-JDS-9DW-7SN-4CE-TDS-7DW" },
			new String[] {
					"S",
					"E",
					"WENENEWNWSSNWNSSSEWWNNWNSNEESENWWNEWSSEENNSSEWWWSESE",
					"1NS-PAW-3NN-PAE-PAS-PAW",
					"TSW-3SN-ASE-5SS-AHE-4HS-7HW-6HN-2SE-JSS-8SW-4SN-QCS-ACW-4CN-3CE-JHW-9HN-5HE-KHS-JCS-2CW-6CN-5CE-QHS-8HW-9CN-2HE-KSS-9SW-2DN-7SE-3DS-7DW-ADN-6DE-9DN-7CE-KDS-8DW-4DS-JDW-QDN-3HE-KCN-THE-5DS-TCW-TDN-QSE-6SS-8CW" },
			new String[] {
					"W",
					"A",
					"NWSWNNSWSWNNSWSESNEWEWSNWSENEWNWNWESESSSNNESWENEEWEE",
					"PAW-PAN-PAE-1NS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"3CW-2CN-4DE-4CS-3DS-KDW-6DN-7DE-2DW-QDN-9DE-5DS-3HN-4HE-JHS-5HW-AHS-7HW-6HN-2HE-KHS-9HW-8HN-THE-ADS-8DW-3SN-8SE-JDS-TDW-4SN-5SE-ACS-5CW-6CN-TSE-TCS-JCW-KCN-JSE-QCN-KSE-8CS-9CW-7CN-QHE-2SS-7SW-9SN-ASE-6SS-QSW" },
			new String[] {
					"N",
					"L",
					"EWNSWNWENWSSSEEENENSWENWSWWNSNWWNSEEWSESESENWSESNWNN",
					"PAN-PAE-1NS-PAW-2CN-PAE-2SS-PAW-3SN-PAE-3NS-PAW-4SN-PAE-PAS-PAW",
					"6CW-TCN-9CE-5CS-ASN-3SE-2SS-7SW-KSN-5SE-4SS-QSW-JSN-9SE-8SS-7HW-3HN-AHE-4HS-2HW-JHE-KHS-6HW-5HN-ACS-3CW-4CN-2CE-KCS-8CW-7CN-THE-QCS-JCW-8HN-2DE-9HS-QHW-6SN-3DE-5DN-6DE-KDS-ADW-QDW-7DN-4DE-8DS-9DW-JDN-TDE-TSS" },
			new String[] {
					"E",
					"N",
					"NEENNWEEWESSSSENSNWNWWSSWEWWNWNSNSNWSNSWWENSEEEEESNW",
					"PAE-2NS-PAW-3DN-PAE-3HS-PAW-3NN-PAE-PAS-PAW",
					"TDW-4DN-ADE-2DS-3CE-ACS-7CW-2CN-6SS-ASW-5SN-7SE-KDW-6DN-3DE-5DS-7DW-8DN-4CE-JDS-AHS-5HW-4HN-4SE-QHS-2HW-6HN-8SE-9HS-3HW-8HN-8CE-7HS-JHW-KHN-9CE-THN-JCE-QDS-TCW-KSN-9SE-QSS-2SW-6CN-JSE-KCS-9DW-QCS-3SW-5CN-TSE" },
			new String[] {
					"S",
					"E",
					"WESEEWNNWESSSWWENNEESNWSWSNSSNSWNEEWEWSENNWNNEWWESNS",
					"2DS-PAW-2HN-PAE-3NS-PAW-4SN-PAE-PAS-PAW",
					"4DE-QDS-KDW-5DN-TSW-3SN-2SE-QSS-ASS-5SW-4SN-8SE-ACS-2CW-8CN-6CE-KCS-7CW-9CN-3CE-QCS-TCW-6DN-5CE-4CS-9SW-2HN-JCE-2DW-TDN-7DE-9DS-KSN-JSE-3HS-7HW-5HN-9HE-AHS-JHW-ADS-3DW-8HN-8DE-6HS-KHW-7SN-QHE-6SN-THE-4HS-JDW" },
			new String[] {
					"W",
					"A",
					"NENEESEEWSWSSNSSNEWWSSENNWWWWESSEWSWSNWNNSENEENWNWNE",
					"1HW-1SN-PAE-1NS-PAW-3SN-PAE-3NS-PAW-PAN-PAE",
					"4HW-KHN-8HE-6HS-JSN-7SE-4SS-QSW-AHW-2SN-5HE-7HS-QCW-2CN-3CE-ACS-9DS-ADW-2DN-6DE-2HW-3SN-JDE-THS-3DS-8DW-KDN-5CE-QDN-5SE-4DS-7DW-4CN-6CE-JCS-TCW-TDS-3HW-5DN-8SE-QHS-9HW-6SN-8CE-KCS-JHW-KSN-9CE-7CS-TSW-9SN-ASE" },
			new String[] {
					"N",
					"N",
					"NWWSSSNEEEWNNSSWNNSEWWESWWSSESNWEEENNESNWESENNEWNWWS",
					"PAN-PAE-PAS-1DW-X1N-1HE-2CS-2SW-3CN-3HE-PAS-5DW-PAN-PAE-PAS",
					"ACN-9CE-5CS-QCW-7SN-4SE-ASS-3SW-AHS-7HW-6HN-4HE-5SS-KSW-2SN-6SE-ADW-6DN-8DE-2DS-KDW-5DN-JDE-3DS-TDW-2CN-8HE-QDS-6CS-3CW-KCN-TCE-8SN-9SE-7DS-TSW-7CS-4CW-8CN-JCE-KHE-5HS-9DW-QHN-4DW-JHN-THE-3HS-QSW-JSN-9HE-2HS" },
			new String[] {
					"E",
					"E",
					"WNENNEESNNSNSSWSNWSWNWWEWNEESNSSWWESESNESESWEEEWNNWW",
					"PAE-PAS-1DW-1NN-PAE-2DS-PAW-2HN-PAE-4HS-PAW-PAN-PAE",
					"QDE-2DS-6DW-ADN-5HN-2HE-JHS-9HW-4HS-8HW-AHN-3HE-3CN-4CE-ACS-2CW-KHS-3DW-5DN-THE-6HS-6SW-9DN-QHE-7CE-QCS-8DW-5CN-9CS-TDW-KCN-8CE-JCN-2SE-3SS-JDW-TCN-4SE-5SS-TSW-6CN-7SE-4DS-KSW-JSN-8SE-7HS-ASW-7DS-KDW-QSN-9SE" },
			new String[] {
					"S",
					"A",
					"SEWSNNSSSWESNENEWENEEWNSNWNEEEENSEWWSNSNSWWWSENWNWWS",
					"1DS-1SW-2SN-PAE-3CS-PAW-3DN-PAE-3NS-PAW-5CN-PAE-6CS-PAW-6DN-PAE-6NS-PAW-PAN-PAE",
					"KSW-2SN-8SE-ASS-2CS-JCW-ACN-3CE-6CN-QCE-KCS-4CW-TCS-4SW-7CN-2DE-9CS-5SW-2HN-4DE-8CS-6SW-3DN-6DE-QDS-ADW-7DN-8DE-JHW-KHN-3HE-8HS-KDN-9DE-3SS-5DW-JDN-4HE-7SS-TDW-7HN-9HE-AHS-THW-5CS-QSW-JSN-6HE-QHS-TSW-9SN-5HE" },
			new String[] {
					"W",
					"L",
					"SSEWWESESNEWWENEWSSWSSEWSSNENWEENNNSSEWEEWWSNNWNWNNN",
					"1CW-1SN-PAE-2DS-PAW-2HN-PAE-3DS-PAW-3SN-PAE-3NS-PAW-4SN-PAE-PAS-PAW",
					"7CE-2CS-KCW-JCN-AHW-2HN-7HE-JHS-5HW-4HN-KHE-QHS-3SE-6SS-JSW-QSN-ASN-2SE-3CS-5SW-KSN-4CE-8CS-4SW-TSN-3HE-TCS-9SW-3DN-4DE-ADS-5DW-KDS-8DW-8HN-2DE-6DS-QDW-7SN-JDE-THN-6HE-7DS-5CW-9HN-9CE-9DS-6CW-8SN-QCE-TDS-ACW" },
			new String[] {
					"N",
					"E",
					"SSENEWEWWNSESESSEWEWESSWNSNSSWWENNNNENSWWNWWNSNWEENE",
					"PAN-1DE-X1S-PAW-2DN-PAE-3DS-PAW-4HN-PAE-5DS-PAW-6HN-PAE-PAS-PAW",
					"5DE-3DS-8DW-KDN-2HN-7HE-AHS-5HW-3HS-6HW-KHN-QHE-KSN-ASE-8SS-2SW-2DE-ADS-6DW-4SN-4DS-QDW-8HN-7DE-7SN-JSE-4HS-3SW-ACS-7CW-5CN-4CE-TDS-5SW-9SN-9DE-JDS-9CW-JCN-6CE-QCS-TCW-JHN-KCE-THN-QSE-3CS-TSW-9HN-8CE-2CS-6SW" },
			new String[] {
					"E",
					"A",
					"WWWSEWWSSENWWSWSNENWNNSWSSWENENENEENEWSNENSNEESSWSEN",
					"PAE-1DS-2CW-X1N-PAE-2SS-3CW-3SN-PAE-PAS-PAW",
					"ACW-QCN-6CE-5CS-JSW-2SN-KSE-5SS-JCE-9CS-7CW-4SN-4HN-7HE-AHS-2HW-9SS-2CW-6SN-7SE-ADS-3DW-5DN-6DE-KDS-8DW-7DN-3SE-3HE-TSS-KHW-6HN-TCS-KCW-ASN-5HE-9DN-8SE-2DS-QDW-QHE-QSS-8CW-JHN-JDS-4CW-TDN-THE-4DS-3CW-8HN-9HE" },
			new String[] {
					"S",
					"L",
					"SENWNNWWSNESWNEEWWSNEENNWSSSESSWESWESNESENWEWEWNWNNS",
					"1HS-PAW-1SN-PAE-2HS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"3DE-7DS-KDW-2DN-7SW-TSN-3SE-2SS-4SN-6SE-ASS-5SW-2HS-7HW-KHN-AHE-TDE-ADS-6DW-8DN-2CS-ACW-4CN-3CE-5DW-JDN-4DE-3HS-KSN-8SE-5HS-9SW-QSN-QCE-6HS-JSW-6CN-9DE-KCS-5CW-QHS-THW-7CN-4HE-TCS-8CW-JCN-8HE-QDN-JHE-9HS-9CW" },
			new String[] {
					"N",
					"A",
					"WSSNWNNSNSSWWSNWWNSSSEEWSSWENEWEENEENESWNNWEENNEWSEW",
					"PAN-PAE-1DS-PAW-PAN-1HE-2HS-PAW-2SN-PAE-3CS-PAW-PAN-PAE",
					"6HW-4HN-3HE-AHS-QCS-6CW-5CN-5HE-ADS-4DW-3DN-TDE-KDS-5DW-6DN-JDE-7DS-QDW-7CN-7HE-TCN-8HE-3CS-2CW-8CN-THE-4CS-KCW-ACW-3SN-JHE-9CS-2HW-QHN-KHE-QSS-KSE-JCS-ASW-9SN-9DS-JSW-9HN-TSE-8DS-5SW-8SN-7SE-2DS-2SW-4SN-6SE" },
			new String[] {
					"E",
					"L",
					"SSNEWNNNEWWSNSSEWWESENWWESNSSWEEWSEEENWNNSESWENNWNSW",
					"PAE-PAS-1NW-PAN-2DE-PAS-2HW-PAN-PAE-2SS-PAW-PAN-PAE",
					"AHW-2HN-QHE-3HS-QDW-TDN-7DE-ADS-4HS-8HW-KHN-7HE-2SN-5SE-KSS-ASW-5DW-3SN-4DE-2DS-4CN-5CE-KCS-6CW-6SS-7SW-TSN-8SE-ACN-TCE-2CS-JCW-9CN-9DE-3CS-QCW-6DW-9SN-KDE-3DS-QSN-JHE-4SS-JSW-8CN-THE-8DS-JDW-7CN-6HE-9HS-5HW" },
			new String[] {
					"S",
					"N",
					"WWNSNESWWWWNESSWNWEEWNWSWNESNNWESENNSWSNSEEESNNEEESS",
					"1DS-2CW-PAN-PAE-X1S-PAW-2NN-PAE-PAS-PAW",
					"QSE-ASS-3CW-2SN-AHS-6HW-4HN-2HE-QHS-KHW-5HN-7HE-QCW-4CN-7CE-5CS-4DW-5DN-8DE-QDS-3HS-2CW-JHN-9HE-8SN-TSE-KSS-6DW-3SS-9CW-9SN-JSE-ACE-8CS-TCW-6CN-7DE-2DS-JDW-ADN-THN-4SE-8HS-JCW-KCN-5SE-3DS-9DW-TDN-6SE-7SS-KDW" },
			new String[] {
					"W",
					"E",
					"NWEWWWENEENSSESEWSEWSNWSESEWNESSSNNWWSWWSEESWENNNNNN",
					"PAW-1SN-PAE-2DS-PAW-2SN-PAE-3CS-PAW-3SN-PAE-3NS-PAW-5CN-PAE-6NS-PAW-PAN-PAE",
					"AHW-4HN-5HE-6HS-QHW-9HN-2HE-KHS-ACS-7CW-2CN-8CE-KCS-3CW-9CN-4CE-6SS-7SW-9SN-4SE-TSN-5SE-3SS-2SW-JSN-8SE-7HS-5CW-QSN-2DE-8HS-6CW-QCN-TCE-3DS-5DW-KSN-4DE-6DS-8DW-ASN-JCE-9DS-JDW-TDN-7DE-QDS-3HW-ADS-JHW-THN-KDE" },
			new String[] {
					"N",
					"L",
					"EWENEENEENWNSWNSNWSESWNWSWNWNSWSWEESESNNSNEWNEWWESSS",
					"PAN-PAE-2NS-PAW-3NN-PAE-PAS-PAW",
					"6DW-3DN-8DE-9DS-ACS-3CW-5CN-7CE-ASS-6SW-2SN-5SE-KSS-9SW-4SN-8SE-QSS-TSW-7SN-JSE-3SS-2DW-8CN-2CE-5HS-3HW-AHN-9HE-KCN-4CE-4DS-QCW-JCN-6CE-7DS-TDW-2HN-THE-JHS-6HW-KHS-8HW-4HN-QHE-7HS-QDW-5DN-9CE-KDS-ADW-JDN-TCE" },
			new String[] {
					"E",
					"N",
					"NENSNSSNNSNESNNEWWSWSSEEEWSWNENEWNWWSSSESEWWEWNNEWEW",
					"1SE-PAS-2DW-PAN-2NE-PAS-4CW-PAN-4SE-PAS-5CW-PAN-6SE-PAS-PAW-PAN",
					"AHS-3HW-4HN-5HE-KHS-8HW-6HN-7HE-2HS-THW-9HN-3CE-5SW-9SN-JSE-3SS-4SE-5CS-QSW-TSN-5DW-3DN-QDE-7DS-KDE-9DS-6DW-2DN-4DE-TDS-ADW-2CN-8DW-4CN-JDE-7CS-KCE-8CS-6SW-6CN-ASW-QCN-KSE-ACS-8SW-TCN-7SE-JCS-JHW-9CN-2SE-QHS" },
			new String[] {
					"S",
					"E",
					"WSSWWWENNSEWWEWNNWSNEESWSNWSNESSNEWSSSNEENENESNWEEWN",
					"PAS-1CW-PAN-1SE-2HS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"5SE-8SS-KSW-ASN-AHN-9HE-3HS-2HW-4HN-5HE-KHS-THW-QHS-7CW-8HN-2SE-JHS-2CW-4SN-8CE-7HS-5CW-6SN-2DE-6HS-6CW-9SN-9DE-JDS-QDW-ADN-TDE-4DN-3SE-KDS-3DW-7DS-6DW-8DN-QCE-5DN-7SE-3CS-KCW-9CN-JSE-4CS-ACW-TSW-TCN-QSE-JCS" },
			new String[] {
					"W",
					"A",
					"WEESWSWESNWWENSNNEWWEEWNSNENSSNWWEEWSSSWESSNNNWESNEN",
					"PAW-1SN-PAE-2CS-PAW-2DN-PAE-3NS-PAW-4DN-PAE-4NS-PAW-5HN-PAE-6SS-PAW-PAN-PAE",
					"THE-AHS-7HW-6HN-KHS-8HW-3HN-2HE-QHS-JHW-JCN-9HE-4SS-2SW-QSN-KSE-ACE-5CS-2CW-6SN-2DN-6DE-KDS-7DW-3DS-8DW-ADN-9DE-7SN-3SE-JSS-9SW-5SS-6CW-ASN-TSE-QDN-TDE-7CS-JDW-8SN-9CE-TCS-KCW-5DN-4CE-5HS-QCW-4DN-3CE-4HS-8CW" },
			new String[] {
					"N",
					"L",
					"NEWEWEESSNESENNENEWSWSWSWWSNNEWSNWSNSESNWEWENESSWNNW",
					"PAN-PAE-1HS-X1W-2HN-2NE-PAS-PAW-PAN",
					"8DS-KDW-2DN-4DE-4CW-JCN-3CE-9CS-8HN-KHE-AHS-6HW-TSS-ASW-7SN-4SE-6CW-2CN-QCE-KCS-9SS-JSW-QSN-8SE-3HN-5HE-THS-9HW-QHS-7DW-4HN-7CE-7HS-9DW-JHN-8CE-KSN-6SE-TCS-3SW-2SN-ACE-2HS-5SW-JDW-3DN-6DE-QDS-TDS-ADW-5DN-5CE" },
			new String[] {
					"E",
					"N",
					"NEEENEWEESEWWWSNSWENNSSWNNWWNSWESNWSESENSNSNWEWSENSW",
					"PAE-1HS-PAW-1SN-2CE-PAS-3CW-PAN-PAE-3SS-PAW-PAN-PAE",
					"7DE-JDS-QDW-ADN-2SN-8SE-TSS-ASW-ACW-2CN-3CE-JCS-7SW-4SN-JSE-KSS-3SS-9SW-QSN-4CE-4DN-5CE-TDS-6DW-5DS-2DW-KDN-7CE-9DN-7HE-3DS-2HW-8DN-QHE-5HS-3HW-4HN-AHE-8HS-6HW-QCE-5SS-8CW-6CN-KHS-THW-9HN-9CE-JHS-KCW-6SN-TCE" },
			new String[] {
					"S",
					"E",
					"NWNNENNSWWESSSWWSSNEWWSNESENEEESNWEENSNWNWWSEEESWSNW",
					"1NS-PAW-2CN-PAE-2DS-PAW-3NN-PAE-PAS-PAW",
					"4SW-KSN-7SE-6SS-2CN-6CE-KCS-3CW-ACS-TCW-4CN-QCE-9CS-JCW-5CN-6HE-2SW-3SN-8SE-TSS-KHS-9HW-3HN-2HE-7HS-4DW-QHN-4HE-8CN-5HE-QSS-3DW-7CN-9SE-2DS-9DW-AHN-THE-5DS-TDW-QDN-KDE-ADS-5SW-JDS-JSW-7DN-8DE-6DS-ASW-8HN-JHE" },
			new String[] {
					"W",
					"A",
					"WESSNENNESNNNEESEESESWESWSENWWWSNWNNWNEWNWWNWSESWESS",
					"PAW-1HN-PAE-1SS-PAW-2CN-2DE-3NS-PAW-4NN-PAE-5HS-PAW-6CN-PAE-6NS-PAW-PAN-PAE",
					"KDW-3HN-6DE-ADS-JCS-2CW-6CN-3CE-5CS-4HW-ACN-7CE-KCN-TCE-4CS-2SW-QCN-2DE-4DS-TDW-9CN-2HE-7DS-4SW-8CN-3DE-8SS-5SW-3SN-9SE-KSS-7SW-7HS-5HW-JHN-AHE-5DE-9DS-6HW-8HN-QDS-JSW-6SN-8DE-ASS-QHW-KHN-QSE-TSS-9HW-THN-JDE" },
			new String[] {
					"N",
					"N",
					"NNSNSWESEWSSSWWSNWNWSESWSENENNSWNNEESEWWENSENWWEEENW",
					"PAN-PAE-1CS-PAW-PAN-1SE-2DS-PAW-3CN-PAE-PAS-PAW",
					"ASW-4SN-QSE-5SS-2DW-7DN-ADE-4DS-TDE-KDS-3DW-5DN-ACS-7CW-2CN-8CE-KCS-JCW-3CN-TCE-JDS-6DW-2HN-3HE-9DS-QDW-5CN-6SE-KSN-3SE-6HS-2SW-4HN-THE-QHS-AHW-8DW-9HN-KHE-QCS-9CS-7HW-8HN-JHE-6CS-9SW-5HN-JSE-4CS-8SW-7SN-TSE" },
			new String[] {
					"E",
					"E",
					"SWSEWNNSESSESEWSSENESNESWSWSSWWEWWNNEENWWNWNNNWEENEN",
					"1DE-2CS-PAW-2DN-PAE-3DS-PAW-3SN-PAE-4CS-PAW-4SN-PAE-5DS-PAW-5SN-PAE-6CS-PAW-PAN-PAE",
					"KDW-7DN-6DE-ADS-QDS-3DW-TDN-2DE-4DS-2HW-7CN-8DE-ASN-TSE-3HS-5SW-4SN-JSE-2CS-3SW-5DS-2SW-8CN-JDE-AHN-7HE-4HS-5HW-6SN-KSE-4CS-9SW-ACS-3CW-7SN-5CE-JCS-6CW-8SN-KCE-KHE-9CS-6HW-THN-QCS-9HW-JHN-TCE-9DS-8HW-QSN-QHE" },
			new String[] {
					"S",
					"A",
					"EENESSNWSWSWSNENESNEWSNWSWEWWSNSNWSNWNNNWWEESNEEWEES",
					"1CS-PAW-1HN-2SE-3HS-4SW-PAN-PAE-PAS",
					"5HS-3HW-JHN-2HE-AHN-TSE-7HS-4HW-KSE-ASS-3SW-8SN-6DS-9DW-JDN-3DE-2SN-6SE-7SS-JSW-4SW-8CN-9SE-6CS-3CE-7CS-JCW-4CN-9HW-6HN-QSE-THS-2CE-TCS-9CW-2DN-ACS-KCW-4DN-5CE-QCS-QHW-7DN-5SE-5DE-TDS-ADW-8HN-QDW-KHN-8DE-KDS" },
			new String[] {
					"W",
					"L",
					"NNEWESWEESEENEWESSWSWWSNSEWNESNEWNWWNSNNWSWNSEESNWNS",
					"PAW-1HN-2CE-2DS-PAW-2SN-PAE-3SS-PAW-4CN-PAE-4SS-PAW-4NN-PAE-5DS-PAW-6SN-PAE-PAS-PAW",
					"4CE-JCS-8CW-2CN-4SS-5SW-JSN-9SE-QDN-ADE-5DS-7DW-7HE-KHS-8HW-3HN-KDS-3DW-3CN-2DE-TSS-3SW-2SN-8SE-ASS-QSW-6SN-6CE-7CS-5CW-ACN-9CE-AHN-4HE-5HS-2HW-QHN-TCE-6DS-THW-9HN-QCE-7SS-JHW-JDS-TDW-KSN-4DE-6HN-KCE-8DS-9DW" },
			new String[] {
					"N",
					"E",
					"WNSEWWSNSWWSENNWSWEWEEESSEWSSNSWNSEEWNNWSENNNWEEENSN",
					"1SN-PAE-3SS-PAW-PAN-4DE-PAS-PAW-PAN",
					"KSS-2SW-5SN-4SE-3SS-8SW-QSN-TSE-3DN-TDE-QDS-4DW-3HS-2HW-KHN-JHE-2DN-ADE-5DS-6DW-JSE-4HS-8DW-6SN-QCW-9CN-5CE-KCS-6HS-QHW-AHN-THE-ASN-9SE-9HS-2CW-7SN-9DE-KDS-6CW-TCS-JCW-3CN-ACE-JDE-8CS-7HW-8HN-7DE-4CS-7CW-5HN" },
			new String[] {
					"E",
					"A",
					"WSWWNSNESENESWNWNSESSWWNSNWSEEWSNSEESSEWNNWEWNEWENEN",
					"1HE-PAS-PAW-X1N-PAE-2NS-PAW-3SN-PAE-3NS-PAW-PAN-PAE",
					"6HW-8HN-AHE-3HS-JHE-QHS-2HW-6CN-3CS-2CW-QCN-KCE-4HE-7HS-4CW-3SN-6DS-4DW-QDN-7DE-8CN-JCE-ACS-5CW-TCS-7SW-4SN-9CE-7CS-2SW-8SN-6SE-8DS-TDW-ADN-5HE-ASN-9SE-9DS-5SW-3DN-THE-KDS-2DW-KHS-JDW-5DN-KSE-9HS-TSW-QSN-JSE" },
			new String[] {
					"S",
					"L",
					"ENSNENSWWSNSWNENSNWENNWEWEEWNNSWEWSSWNWEEWESSSNEWESS",
					"1SS-PAW-1NN-PAE-2SS-3HW-PAN-PAE-PAS",
					"9SN-2SE-ASS-4SW-5DS-JDW-2DN-3DE-KDW-4DN-ADE-6HS-THS-QHW-KHN-2HE-TDN-QDE-JHS-7DW-4CS-ACW-7CN-2CE-JSW-5HN-3SE-6SS-QCN-6CE-8CS-TCW-4HN-8HE-7SS-3HW-QSE-KSS-9CW-3CN-8SS-AHW-5CN-TSE-9HW-9DN-5SE-KCS-7HW-6DN-8DE-JCS" },
			new String[] {
					"W",
					"N",
					"NWESSSEWWSNNEWEWSSSSNWESNNWWENEWWWEWNSSSNNNWENENSEEE",
					"PAW-1SN-PAE-2NS-PAW-3NN-PAE-PAS-PAW",
					"7HW-5HN-THE-KHS-JCS-3CW-2CN-ACE-6HE-AHS-2HW-QHN-5CS-9CW-QCN-8CE-KCN-4CE-6CS-TCW-ADN-3DE-5DS-2DW-KDN-JDE-6DS-4DW-9DN-4HE-QDS-TDW-8DS-3HW-3SN-7SE-7DS-8HW-4SN-9SE-7CS-9HW-5SN-QSE-JSS-6SW-TSN-ASE-KSE-2SS-JHW-8SN" },
			new String[] {
					"N",
					"A",
					"NNNWWSSWSSSWNSWEWEWENWSWNEEWSEWEEWSNSWNNSENEESNNNEES",
					"1SN-PAE-2CS-PAW-3CN-PAE-4SS-PAW-PAN-PAE",
					"5HE-QHS-KHW-AHN-JHN-2HE-4HS-3HW-JSN-QSE-ASS-3DW-THS-6HW-9DN-7HE-QCS-6CW-2CN-7SE-KSE-3SS-5DW-2SN-6DE-2DS-TDW-KDN-TSN-4SE-8SS-5CW-9SN-6SE-JDS-7DW-ACN-4DE-7CS-9CW-3CN-8DE-TCS-KCW-QDW-5SN-ADE-8CS-4CN-8HE-JCS-9HW" },
			new String[] {
					"E",
					"L",
					"SESNNSNENWNSWSEESEEEWNNENWNSNSEEWWSWWWSNSWWWSEEENNSW",
					"PAE-1CS-X1W-2CN-2DE-PAS-2HW-3CN-PAE-PAS-X1W-PAN-3HE-PAS-3SW-PAN-4HE-PAS-PAW-PAN",
					"5CN-3CE-KCS-ACW-ASW-2SN-8SE-3SS-QHW-4HN-6HE-AHS-2CS-JCW-QCN-9CE-2HN-7HE-THS-KHW-8HW-TDN-3DE-3HS-5SW-JSN-9SE-7SS-TCN-4DE-4CS-JHW-9HW-QSN-TSE-5HS-ADW-JDN-6DE-2DS-9DW-KDN-7DE-5DS-8CN-QDE-7CS-6SW-6CN-8DE-KSS-4SW" },
			new String[] {
					"S",
					"N",
					"SEESWNEWNESSSWWWWNEESSSNWSENENWSEWWSNNENSWEWNNWESNNE",
					"1CS-PAW-1SN-PAE-2DS-PAW-2HN-PAE-2NS-PAW-3NN-PAE-PAS-PAW",
					"3DW-6DN-8DE-9DS-TDS-2DW-QDN-7DE-3HN-4HE-JHS-6HW-JSS-4SW-2SN-5SE-3SS-6SW-QSN-ASE-4CE-2CS-9CW-TCN-KSN-TSE-5CS-9SW-8SN-2HE-7HS-6CW-7SN-8HE-JDS-4DW-7CN-8CE-QCS-9HW-ACS-KDW-KHN-JCE-KCS-5DW-QHN-3CE-ADS-THW-5HN-AHE" },
			new String[] {
					"W",
					"E",
					"NWWSSSWSWEESWNSEENNWNNWENWNSEENSSESNWSNNWNESEEWWEEWS",
					"1CW-1DN-1SE-2HS-2SW-4HN-4SE-PAS-PAW-PAN",
					"7HS-QHW-AHN-4HE-2CN-QCE-KCS-ACW-3SW-4SN-8SE-ASS-3DS-ADW-7DN-4DE-3CW-2SN-JCE-5CS-KDN-5DE-3HS-8DW-2DN-QDE-6SS-JDW-6CS-4CW-6DN-7SE-5HE-8HS-9SW-2HN-8CW-9DN-5SE-7CS-9HE-THS-TSW-6HN-KSW-TDN-QSE-9CS-TCW-JHN-JSE-KHS" },
			new String[] {
					"N",
					"L",
					"WWSEWSWNWNSSNESSENWWNWEWSWEENNESNNWEEWENNSNSNWSSEEES",
					"PAN-1HE-1SS-X1W-3SN-PAE-PAS-PAW",
					"KHW-4HN-6HE-7HS-THW-5HN-JHE-4SS-4CS-2CW-ACN-5CE-JCN-2DE-7CS-3CW-9CN-5DE-QCS-6CW-KCS-8CW-6DN-JSE-QHE-TSS-7DW-8HN-ASS-8SW-2SN-QSE-6SS-8DW-7SN-KSE-JDE-KDS-ADW-9DN-TCW-9HN-2HE-9SS-4DS-QDW-5SN-AHE-3SN-3HE-3DS-TDW" },
			new String[] {
					"E",
					"N",
					"SNWWEWSWWSNWNNSSWSEENNSSNEEWEWSENNSEESNEWNWESNENEWWS",
					"PAE-PAS-PAW-1DN-1HE-2HS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"4HE-6HS-5HW-8HN-TDN-7DE-3DS-5DW-KDN-ADE-4DS-3HW-QHE-KHS-7CW-9HN-JCS-4CW-3CN-6CE-2CS-5CW-QCN-8DE-9DN-2HE-6DS-9CW-2DN-7HE-JDS-3SW-QDS-TCW-4SN-JHE-8CS-KCW-ACN-2SE-AHN-6SE-THS-5SW-8SN-9SE-ASS-QSW-7SS-KSW-TSN-JSE" },
			new String[] {
					"S",
					"E",
					"NENNEWWESWNSESWENSWWWEWSWSENEWWNEEESWSNSSNSSNNNEEWNS",
					"1SS-PAW-4DN-PAE-4NS-PAW-5DN-PAE-6SS-PAW-PAN-PAE",
					"7CW-2CN-ACE-TCS-3CE-KCS-8CW-4CN-ASS-QSW-4SN-TSE-2SS-JCW-KSN-JSE-QCN-6CE-2DS-7DW-AHN-2HE-JHS-5HW-3HN-8HE-KHS-6HW-ADS-3DW-5DN-4DE-6DS-8DW-7SN-TDE-5CN-9CE-3SS-9DW-QDS-KDW-8SN-4HE-9SN-THE-6SS-JDW-7HN-9HE-5SS-QHW" },
			new String[] {
					"W",
					"A",
					"NWENWSSSWNEESSSNNESWEWEWWESNNSNENWNNSNWSEWENWEWWESES",
					"PAW-3HN-X1E-PAS-4SW-PAN-PAE-PAS",
					"JHN-7HE-2HS-AHW-7SW-6SN-KSE-ASS-QSS-4SW-5DN-3SE-2SS-TSW-4DN-5SE-8DW-6HN-6DE-2DS-KDW-3HN-9DE-3DS-TDW-4HN-ADE-7DS-JDE-5HS-QDW-8HN-3CW-2CN-QCE-ACS-9CS-TCW-JCN-4CE-THN-8SE-QHS-9HW-JSE-8CS-9SW-5CN-KCE-7CS-6CW-KHN" },
			new String[] {
					"N",
					"L",
					"WSEWSNSEEWNNNNWEENNENWNESSSWWSESWWWEWNWSNSNWEEESSNSE",
					"1DN-PAE-1SS-3HW-PAN-PAE-3SS-PAW-4SN-PAE-PAS-PAW",
					"2CW-ACN-4CE-3CS-3SN-8SE-TSS-6SW-KSS-3HW-5SN-ASE-7SE-2SS-4HW-QSN-2DN-5DE-KDS-3DW-JSS-8HW-KHN-9SE-ADS-TDW-6DN-4DE-6CS-5CW-KCN-9CE-JDN-8DE-2HS-JCW-9DN-QDE-4SS-9HW-8CS-THW-QCN-TCE-7CN-JHE-7HS-AHW-7DN-6HE-5HS-QHW" },
			new String[] {
					"E",
					"N",
					"WSNWENWEENEWSSNSENENSESEWSSWSNSEWNNSSEWWEWWNNNEWSNEW",
					"PAE-1HS-1SW-PAN-2HE-PAS-3CW-PAN-3SE-4DS-PAW-4HN-5CE-X1S-5SW-PAN-PAE-PAS",
					"THN-7HE-2HS-AHW-2SW-7SN-9SE-JSS-4HS-3HW-5HN-KHE-5DE-ADS-KDW-3DN-ACS-2CW-4CN-6CE-3CS-5CW-7CN-9CE-3SE-2DS-ASW-6SN-4SW-8SN-KSE-6HS-QDE-4DS-8HW-6DN-TCE-JHS-KCW-JCN-8CW-8DN-QCE-QHS-7DE-9DS-TSW-9HN-5SW-QSN-TDE-JDS" },
			new String[] {
					"S",
					"E",
					"WSWSNESEEEEWSNENNSEEWEWNEWSSNSSENWSWWWSNNWWSNNNSEENW",
					"2DS-X1W-2HN-3DE-PAS-3NW-PAN-4DE-PAS-PAW-PAN",
					"TSS-4SW-KSN-JSE-6CN-JCE-ACS-2CW-3CS-4CW-5DN-7CE-2SN-QSE-6SS-5SW-TDE-6DS-9DW-QDN-8HN-7HE-AHS-9HW-5CS-KCW-2DN-TCE-3SN-8DE-2HS-ASW-3DE-8CS-JDW-4DN-ADW-4HN-KDE-THS-KHW-9SN-7DE-6HS-QCE-5HS-QHW-8SN-9CE-3HS-JHW-7SN" },
			new String[] {
					"W",
					"A",
					"WENEENSSEWSNESSNSWEWWNSSWEESWNSSSSNEWNEWNWNENNWEENWW",
					"1SW-PAN-2CE-2DS-2NW-PAN-4SE-PAS-PAW-PAN",
					"TDN-ADE-2DS-6DW-JSE-3HS-ASW-3SN-4HW-5HN-JHE-6HS-7DE-QDS-KDW-4DN-2CW-4CN-TCE-QCS-7HS-QHW-KHN-AHE-2HE-8HS-4SW-THN-JCW-7CN-ACE-8CS-3CE-9CS-9SW-KCN-KSW-5SN-6SE-3DS-9DW-7SN-TSE-5DS-6CE-JDS-2SW-QSN-8SN-5CE-9HS-8DW" },
			new String[] {
					"N",
					"N",
					"WSENWSNEEWWSESNNWWWEEWEWNNENSNEESESSSNSNSSEWNSENWWWN",
					"1DN-PAE-1HS-X1W-1SN-X1E-3HS-PAW-4HN-PAE-PAS-PAW",
					"QCW-5CN-ACE-3CS-7HE-AHS-2CW-3HN-KCS-6CW-8CN-4CE-7CS-JCW-KHN-9CE-5HN-6HE-QHS-5DW-JHS-6SW-2SN-2HE-THS-6DW-7SN-9HE-2DS-7DW-ADN-8DE-KDN-9DE-3SS-TDW-3DN-JDE-4HS-QDW-4SS-JSW-ASN-5SE-4DN-TCE-8SS-QSW-TSN-9SE-8HS-KSW" },
			new String[] {
					"S",
					"A",
					"WSNSSNENWESSWSWWEWNEEWSESEWSENWSENWWESSSNNEENNNWWENN",
					"1NS-PAW-2HN-PAE-2SS-PAW-4SN-PAE-PAS-PAW",
					"JHW-5HN-4HE-AHS-2SS-TSW-3SN-5SE-ACW-4CN-JCE-3CS-TCW-7CN-8CE-QCS-KHS-2HW-9HN-8HE-3HS-6HW-4SN-QHE-ASN-6SE-7HS-JSW-KSN-QSE-2DS-2CW-9CN-5DE-KCS-3DW-6CS-4DW-7DN-8DE-5CS-TDW-9SN-ADE-8SN-QDE-KDS-6DW-7SN-9DE-JDS-THW" },
			new String[] {
					"N",
					"E",
					"SEESWWSNNENNESNWEENSWSESWSWWWSENNNNWESSNWEEWWNESEWSN",
					"PAN-PAE-1NS-PAW-2CN-PAE-2DS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"2HW-7HN-QHE-AHS-2CS-7CW-KCN-ACE-5DE-TDS-KDW-3DN-3HW-8HN-6HE-5HS-7DN-6DE-ADS-4DW-QDS-9DW-9CN-JDE-5CS-6CW-QCN-3CE-9HN-4SE-KHS-4HW-8DS-3SW-TCN-4CE-2DS-6SW-THN-5SE-KSS-7SW-2SN-9SE-TSS-QSW-ASN-JSE-8SN-JCE-8CS-JHW" },
			new String[] {
					"E",
					"A",
					"NEESWSENSSNWSESESSWSSNNNENWWWSWNWENNSWNEWEENEEWEWWSN",
					"PAE-PAS-PAW-1DN-PAE-2DS-2HW-3NN-PAE-PAS-PAW",
					"9HE-QHS-KHW-AHN-ADN-2DE-3DS-7DW-QDN-KDE-5DS-JSW-7SE-KSS-9SW-6SN-6DS-2HW-TDN-4DE-JDN-3CE-8DS-3HW-QCN-4CE-5CS-KCW-4HW-JHN-8CE-5HS-THN-2SE-7CS-6HW-ASN-4SE-TCS-3SW-2CN-5SE-JCS-6CW-ACS-8HW-9CN-TSE-9DS-QSW-7HN-8SE" },
			new String[] {
					"S",
					"L",
					"NNWNESSWSSSWSWWSEEWSENSSNEENWNEWNWSWNNEENWESWWNSENEE",
					"1HS-PAW-4HN-4NE-PAS-5CW-PAN-PAE-PAS",
					"KHN-AHE-THS-4HW-ASE-6SS-4SW-3SN-2HE-TSS-JHW-QHN-3HN-6HE-7CS-7HW-TCS-4CW-2CN-6CE-QDS-3DW-TDN-ADE-KSE-8CS-8SW-9SN-4DS-2DW-KDN-5DE-5HN-2SE-JCS-9HW-JDS-7DW-3CN-6DE-QSN-5SE-8DS-7SW-5CN-9DE-ACS-9CW-QCS-KCW-8HN-JSE" },
			new String[] {
					"W",
					"N",
					"WEWESSWEENSSEEENENSSNEENSSEWSNENNWSNSWWNWNWWNSWEWWNS",
					"PAW-PAN-PAE-1DS-1SW-X1N-PAE-2CS-PAW-2DN-PAE-2NS-PAW-3DN-PAE-3NS-PAW-PAN-PAE",
					"QSW-2SN-TSE-ASS-7DS-3HW-QDN-2DE-4DN-TDE-KDS-3SW-6CS-2CW-JCN-ACE-TCE-QCS-4CW-6DN-4HS-KHW-5HN-6HE-AHW-7HN-2HE-THS-8CW-4SN-3CE-KCS-QHS-9HW-8HN-5CE-8SS-5SW-KSN-3DE-JHN-9CE-8DS-6SW-9DN-JDE-ADS-9SW-7CS-JSW-7SN-5DE" },
			new String[] {
					"N",
					"A",
					"WNWNEWSWSNESESWSSNWSESSENNSNNEENWEWENSEWNEWWWNESWENS",
					"1CN-1HE-2DS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"6HE-KHS-8HW-3HN-2DS-7DW-ADN-9DE-KDN-QDE-4DS-3DW-3CN-ACE-8CS-7CW-5HE-2HS-THW-QHN-5CN-6CE-TCS-2CW-JDS-4CW-6DN-QCE-TDS-9CW-4HN-9HE-8DS-2SW-7HN-JHE-5DS-5SW-3SN-AHE-ASS-6SW-8SN-4SE-TSS-7SW-KSN-9SE-JCN-QSE-KCS-JSW" },
			new String[] {
					"E",
					"L",
					"NEEWWESNSWNENWNSWESWNEWSSNWSSWWWNESNESEEWENSSENENNWS",
					"PAE-PAS-PAW-1CN-PAE-1HS-PAW-1SN-PAE-2DS-PAW-2NN-PAE-3NS-PAW-PAN-PAE",
					"TDE-4DS-5DW-ADN-8HN-AHE-3HS-7HW-3CE-TCS-JCW-QCN-JHN-9HE-4HS-2HW-3DN-6DE-KDS-2DW-6SS-KSW-5SN-4SE-6CW-ACN-4CE-8CS-9SN-2SE-ASS-3SW-7SS-5CW-JSN-8SE-QSN-TSE-7DS-5HW-9DN-7CE-QDS-8DW-KHS-6HW-2CN-QHE-THS-JDW-9CN-KCE" },
			new String[] {
					"S",
					"N",
					"NSWEWSWNESWSWSNEWNSNNEWNSSWWSEWNEESSSSEENNWENWNWEEEN",
					"1HS-PAW-1SN-PAE-2NS-PAW-3SN-PAE-3NS-PAW-PAN-PAE",
					"6CW-2CN-5CE-7CS-KHS-2HW-7HN-AHE-KSE-3CS-8SW-ASN-3DN-4DE-ADS-5DW-QHS-3HW-3SN-5HE-JHS-6HW-4SN-8HE-THS-4CW-7SN-9HE-4HS-8CW-9SN-2SE-KDS-JDW-6DN-TDE-2DS-QCW-QDN-TCE-9DN-6SE-7DS-5SW-8DN-JSE-JCS-TSW-9CN-QSE-KCS-ACW" },
			new String[] {
					"W",
					"E",
					"WSNNSSNENEESSESENNSNWENNWNNSSWEWWWSNWEWWWSESEWWNESEE",
					"PAW-2DN-2SE-3DS-4SW-5DN-5SE-PAS-PAW-PAN",
					"ACS-2CW-5CN-9CE-3DS-KDW-ADN-2DE-QDN-4DE-7DS-9DW-TCN-QCE-KCS-2SW-3SW-TSN-ASE-4SS-JCE-3CS-5HW-4CN-KHE-3HS-7HW-2HN-TDE-4HS-8SW-5DN-9SW-6DN-5SE-QSS-THS-QHW-JHN-6HE-AHW-8CN-KSE-6SS-JSE-7CS-9HW-JDN-7SE-6CS-8HW-8DN" },
			new String[] {
					"N",
					"L",
					"NESWNESSSWSWEEENSWNENNWWWENESNSENNNSWESWWEWNESWNWESS",
					"PAN-1DE-X1S-1SW-2HN-PAE-4HS-PAW-PAN-PAE",
					"4SE-ASS-2SW-6SN-5DS-JDW-4DN-3DE-3SW-TSN-QSE-KSS-4CS-5CW-6CN-7CE-7SE-8SS-9SW-2HN-7DN-8DE-4HS-6DW-8CS-JCW-2CN-3CE-KCW-8HN-ACE-9CS-THN-KHE-AHS-QHW-6HS-5SW-9HN-3HE-5HN-7HE-JHS-QDW-QCS-JSW-TDN-ADE-TCS-KDW-9DN-2DE" },
			new String[] {
					"E",
					"N",
					"WWWWNWNESSNNSSENSSEWNNWSESSWSSNSENNNWNEEEWEWEEWSEENW",
					"PAE-1SS-PAW-2HN-PAE-4HS-PAW-PAN-PAE",
					"9CE-ACS-2CW-6CN-2HS-QHW-KHN-AHE-QSE-TSS-ASW-KSN-3HW-9HN-8HE-4HS-TDN-3DE-2DS-JDW-4SW-4DN-2SE-5HS-ADS-8DW-9DN-7DE-5DS-3CW-6HN-KDE-8CN-3SE-TCS-4CW-7HS-9SW-JHN-JSE-THN-8SE-JCS-6SW-KCN-7SE-QDS-7CW-QCN-5SE-6DS-5CW" },
			new String[] {
					"S",
					"E",
					"ESWSNESNWEWNNSWSESWEENWSNSSSWENEWEWWWSNWENNWENENSSNE",
					"1DS-PAW-1SN-PAE-1NS-PAW-2CN-PAE-4SS-PAW-6NN-PAE-PAS-PAW",
					"QHW-AHN-5HE-2HS-4SN-7SE-JSS-6SW-QSS-2SW-5SN-ASE-7HE-KHS-8HW-6HN-3CS-4CW-ACN-2CE-KSN-3SE-3HS-4HW-TSN-9SE-5CS-3DW-8SN-9HE-2DS-THW-KCN-7CE-8CS-TCW-KDN-5DE-4DS-7DW-TDN-8DE-QDS-JDW-ADS-QCW-9CN-9DE-6DS-JHW-6CN-JCE" },
			new String[] {
					"W",
					"A",
					"WSSNWEEENSWESNWSWSNWWEWSNSSNSSENENEWWEWSNNENWEENENSW",
					"1DW-PAN-1HE-PAS-1NW-PAN-PAE-X1S-2DW-PAN-PAE-PAS",
					"TCN-7CE-4CS-QCW-3DW-2DN-TDE-QDS-KSS-ASW-3SN-5SE-JHW-3HN-6HE-2HS-9DW-KDN-8CE-4DS-5CN-9CE-JCS-2CW-ACS-6CW-7HN-KCE-3CS-JDW-9HN-8HE-QHW-7DN-THE-4HS-QSN-8SE-2SS-7SW-4SN-9SE-6DS-8DW-5DW-6SN-KHE-ADS-5HS-AHW-TSN-JSE" }, 
		};
	private static final int[] tabType = new int[]{0,1,2};
	private static final int INDEX_DEALER = 0;
	private static final int INDEX_VULNERABILITY = 1;
	private static final int INDEX_DISTRIB = 2;
	private static final int INDEX_BIDS = 3;
	private static final int INDEX_GAME = 4;
	private static String convArgine = "01000000001000001001011111101101110000102100101120000";
	private static byte[] options = new byte[]{0x00,0x00,0x01,0x00,0x00};
//	private static byte[] optionsBidInfo = new byte[]{0x00,0x03,0x00};


    /**
     * Convert int value to string hexa
     * @param value must be > 0
     * @return
     */
    public static String intToHexaString(int value) {
        StringBuilder sb = new StringBuilder();
        sb.append(Integer.toHexString(value));
        if (sb.length() %2 == 1) {
            sb.insert(0, "0");
        }
        return sb.toString().toUpperCase();
    }

    /**
     * Build options according to result type and engine version
     * @param resultType
     * @param engineVersion
     * @return
     */
    public static String buildOptionsForEngine(int resultType, int engineVersion) {
        int engineSel = 0;
        int engineSpeed = 0;
        // options field : 0=engine selection - 1=engine speed - 2=result type - 3&4=engine version
        String result = "";
        result += intToHexaString(engineSel & 0xFF);
        result += intToHexaString(engineSpeed & 0xFF);
        result += intToHexaString(resultType & 0xFF);
        result += intToHexaString(engineVersion & 0xFF); // lowbyte
        result += intToHexaString((engineVersion & 0xFF00) >> 8); // highbyte
        return result;
    }

    public static WSComputeQuery createQuery() {
        if (EngineConfiguration.getInstance().getIntValue("compute.test.getQueryRandom", 0) == 1) {
            return createRandomQuery();
        } else {
            WSComputeQuery query = new WSComputeQuery();
            query.setDeal(EngineConfiguration.getInstance().getStringValue("compute.test.query.deal", null));
            query.setConventions(EngineConfiguration.getInstance().getStringValue("compute.test.query.conventions", null));
            query.setQueryType(EngineConfiguration.getInstance().getIntValue("compute.test.query.type", 0));
            query.setOptions(buildOptionsForEngine(0, EngineConfiguration.getInstance().getIntValue("compute.test.query.engine", 174)));
            query.setGame(EngineConfiguration.getInstance().getStringValue("compute.test.query.game", null));
            query.setComputeID(0);
            return query;
        }
    }
	
	public static WSComputeQuery createRandomQuery() {
		Random random = new Random(System.currentTimeMillis());
		int idxGame = random.nextInt(gameTest.length);
		int randomType = random.nextInt(tabType.length);
		if (idxGame >= 0 && idxGame < gameTest.length) {
			String[] game = gameTest[idxGame];
			WSComputeQuery query = new WSComputeQuery();
			query.setDeal(game[INDEX_DEALER]+game[INDEX_VULNERABILITY]+game[INDEX_DISTRIB]);
			query.setConventions(convArgine);
			query.setQueryType(randomType);
			String versionMoteurStr = EngineConfiguration.getInstance().getStringValue("compute.test.engine", "619");
			String[] versionMoteurTab = versionMoteurStr.split(";");
			int versionMoteur = Integer.parseInt(versionMoteurTab[random.nextInt(versionMoteurTab.length)]);
			String sOptions = buildOptionsForEngine(versionMoteur, 0);
			query.setOptions(sOptions);
			// bid or bid info
			if (randomType == 0 || randomType == 2) {
				String[] bidsTemp = game[INDEX_BIDS].split("-");
				String bids = "";
				if (bidsTemp.length > 0) {
					try {
						int randomBid = random.nextInt(bidsTemp.length - 1);
						for (int i = 0; i < randomBid; i++) {
							bids += bidsTemp[i].substring(0, 2);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
				query.setGame(bids);
			}
			// card
			else if (randomType == 1) {
				String[] bidsTemp = game[INDEX_BIDS].split("-");
				String bids = "";
				for (int i = 0; i < bidsTemp.length; i++) {
					bids += bidsTemp[i].substring(0, 2);
				}
				String[] cardsTemps = game[INDEX_GAME].split("-");
				String cards = "";
				if (cardsTemps.length > 0) {
					try {
						int randomCard = random.nextInt(cardsTemps.length - 1);
						for (int i = 0; i < randomCard; i++) {
							cards += cardsTemps[i].substring(0, 2);
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
				query.setGame(bids+cards);
			}
			
			query.setComputeID(0);
			return query;
		}
		
		return null;
	}
	
	public static boolean isTestEnable(long userID) {
		if (EngineConfiguration.getInstance().getIntValue("compute.test.getQueryRandom", 1) == 1) {
			String testLogin = EngineConfiguration.getInstance().getStringValue("compute.test.login", "");
			String[] temp = testLogin.split("-");
			for (int i = 0; i < temp.length; i++) {
				if (Integer.parseInt(temp[i]) == userID) {
					return true;
				}
			}
		}
		return false;
	}
	
	public static void main(String[] args) {
		for (int i = 0; i < 100; i++) {
			WSComputeQuery q = createRandomQuery();
			System.out.println("query="+q.toString());
			try {
				Thread.sleep(10);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
}
